### ISSUE TITLE
FTP Accounts: User@Domain.tld

### ISSUE THREAD

**Issue by ghost** [sentora/sentora-core#100]
As requested here: http://forums.sentora.org/showthread.php?tid=20&pid=5652#pid5652

**Comment by denysvitali** [comment]
Isn't user@domain.tlD?

**Comment by MBlagui** [comment]
Nope user name should not be admin@domain.com but instead take a prefix with username
username_myftpuser. This is the norm we use for mysql & should use to separate each user context.

**Comment by TGates71** [comment]
@MBlagui is correct. to keep standards the same, we should keep/change it to accountname_username and make sure mysql users and databases use the same style. changing it to name@domain.tld is more of a request rather than a requirement. this is not cpanel but our own vision ;)

**Comment by bobsta63** [comment]
Added it as a feature request, personally I don't like the idea and I've always preached what @TGates71 said above... 'We're doing things our own way, not necessarily following the likes of cPanel etc.' 

However as and when we get round to it I guess we can run a poll and see who would prefer this requested method for ftp accounts :+1:

**Comment by MBlagui** [comment]
We might later when we have time offer this as config feature choose naming convention for FTP users... Our or full domain... But later as it will require a db field to store the choice

**Comment by denysvitali** [comment]
@MBlagui I was saying that is ".TLD" instead of the title ".TLS" :smile:

**Comment by TGates71** [comment]
We are discussing this, but since it is a feature I will close it and post it in our private task tracker.
