### ISSUE TITLE
Database encoding

### ISSUE THREAD

**Issue by ryucz** [sentora/sentora-core#102]
I noticed that some tables in database, for example x_profiles are in latin1 instead of utf8. This causes weird characters in UTF8 strings.

**Comment by bobsta63** [comment]
Interesting! - I'll fix and push today, thanks for reporting :+1:

**Comment by bobsta63** [comment]
Changes have been made and pushed in the following two commits:-

https://github.com/sentora/sentora-installers/commit/e7130f6ae784fb2ea6679097d681bb998661cab3
https://github.com/sentora/sentora-installers/commit/257b396532b749292172c83b6e24692ff37f6690

I will do another RC release shortly to incorporate this change.
