### ISSUE TITLE
How to upgrade PHP version?

### ISSUE THREAD

**Issue by phoomin2012** [sentora/sentora-core#108]
How to upgrade php version from 5.3 to 5.4?

**Comment by TGates71** [comment]
We do not support upgrading any of the modules that get installed with current installer (which is now released!) as we rely on the version provided by the respective OS repositories to avoid breaking the panel. You may find an answer by a community member who has tried and tested this on our forums: http://forums.sentora.org. Good luck!

**Comment by bachopencart** [comment]
Hi,
1: yum install epel*
2: yum update / yum upgrade
3: 
Code:
CentOS and Red Hat Enterprise Linux 6.x
wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm 
sudo rpm -Uvh remi-release-6*.rpm

CentOS and Red Hat Enterprise Linux 7.x
wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm 
sudo rpm -Uvh remi-release-7*.rpm
4: yum update / yum upgrade
5: yum --enablerepo=remi,remi-php56 update
6: yum --enablerepo=remi,remi-php56 upgrade
7: reboot
8: php -v Big Grin

working on 100%

**Comment by TGates71** [comment]
NOTICE: This will make your install a customized one and support from the staff will be limited if at all. Do so at your own risk!

**Comment by MBlagui** [comment]
you can compile your own php BUT you will need then to setup fastcgi and it's more complicated.

M B

**Comment by syrakozz** [comment]
+1

**Comment by syrakozz** [comment]
@TGates71 the solution is gd, maybe you should release a new version , php 5.3 is so old

**Comment by MBlagui** [comment]
centos 7 ships wth php 5.4 or ubuntu 14 ships with 5.5

**Comment by TGates71** [comment]
it has nothing to do with releasing a new version. The php versions are the defaults installed by the OS's main repositories respectively. As MBlagui mentioned above.

**Comment by thanhhaiqtvn** [comment]
how to upgrade it to PHP 7? thanks.

**Comment by TGates71** [comment]
Not supported at this time. Use our forums for support! http:://forums.sentora.org

**Comment by MBlagui** [comment]
Again upgrading to PHP7 will break all sentora security.

Thanks to discuss this more in the forums.

**Comment by Caffe1neAdd1ct** [comment]
As the above team have stated the sentora security relies on the suhosin
extension which isn't stable on Php 7 yet.

I'm keeping an eye on it and can update when applications start working
correctly with this configuration.
