### ISSUE TITLE
setzadmin and special characters

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-core#109]
used setzadmin to make an easier test password, alpha-numeric works, but used special characters like $ did not work.

**Comment by bobsta63** [comment]
Special characters like '$' won't work as they are seen by the CLI as variables, not really sure how we can combat this but we can look into it I guess.

Thanks or posting Tom - I can however confirm that this is definitely NOT due to us switching to UTF8,

**Comment by TGates71** [comment]
Makes total sense. Maybe use a protected server-side PHP file to do it or some sort of escaping or set the passed password in a variable it's self? Just some thoughts to kick around.

**Comment by bobsta63** [comment]
No, what I'm saying is, that the Linux console interprets the '$' character
and others as special characters on the CLI, escaping them in PHP will not
help at all as the special characters will be intercepted at the CLI and
will never make it  to the PHP script behind to get escaped ;)

**Comment by TGates71** [comment]
I completely see now... well, it's good to use if you can't login and need to reset pw, then make a better password once logged in. I guess this can be closed then. no need to try and hash it out.

**Comment by trojanspike** [comment]
Only when it's wrapped in double quotes will the variable be used

```bash
PARAM=password

echo "param value will show : $PARAM"

echo 'param value will not show - $PARAM'
```

**Comment by bobsta63** [comment]
Try it from the CLI then Lee, I think you'll be surprised... the CLI is
still trying to use strange characters and will need an escape char!

**Comment by trojanspike** [comment]
oh right - PHP not BASH. : got cha

**Comment by bobsta63** [comment]
Closing this as not much we can do - except i guess wrap the parameter values in double quotes " which may work - this is however a limitation with using the CLI tools.
