### ISSUE TITLE
Show/Hide password don't work for FTP

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-core#111]
Minor issue.
Sentora 1.0.0
Showing/Hiding password for FTP password don't work under shadowing.or normal user.

**Comment by TGates71** [comment]
I can confirm that it does work under zadmin (administrator).
Show/hide works shadowing.
Show/hide works user
Using Ubuntu 12.04

**Comment by bobsta63** [comment]
I can also confirm it's the same on Ubuntu 14.04.1 - Gotta be a jQuery/CSS
issue for sure... I've not looked into it yet though!

**Comment by TGates71** [comment]
So, it works for you Bobby or no? If it does work, then possibly a centos issue..?

**Comment by MBlagui** [comment]
This feature was introduced after we moved into RC guys... We should stop messing up front end once we are in RC.

Centos 6/7 don't work.

**Comment by bobsta63** [comment]
Nah... doesn't work bud.. I'm just installing another server atm but will
fix for next release.

**Comment by TGates71** [comment]
Thats odd, as it works just fine for me.

**Comment by bobsta63** [comment]
.......Not for me lol!

**Comment by TGates71** [comment]
Does NOT work on Chrome.

**Comment by SoulTransfer** [comment]
.. fix done..
Quite a bit of changes as the styles looked bad.
My first commit to repository of someone else :)

**Comment by 5050** [comment]
It worked for Firefox (used along design) and probably with IE (because I'm used to test with both them, but I do not remember if I did with IE) but i'm sure I did not checked with chrome, opera and all others. My fault.

@SoulTransfer
Before merging the new version, can you tell us with which browser you checked it, to ensure it continue to work with others than chrome ?

**Comment by SoulTransfer** [comment]
@5050 - one of the rasons for the refactoring and reimplementation in jQuery is the provided API-abstraction by the jQuery Framework. It ensures to have the same set of functions for all Browsers >IE8 (with jQuery 1.10) Therefore I would opt for reimplement "critical" functionality with jQuery... 

I have tested it with the following browsers:
![password](https://cloud.githubusercontent.com/assets/6890413/6315814/670a1efc-ba0f-11e4-83af-f40718a38b96.PNG)

- Chrome 40 [passed]
- Firefox 35 [passed]
- IE11 [passed]
- IE Mobile o Windowshone 8.1 [passed]
- IE9 [passed]
- IE7 [failed] <- This was expected and cannot be changed

**Comment by bobsta63** [comment]
Excelent great stuff, thanks SoulTransfer, I'll merge the changes now... IE7 in my opinion is way too old to worry about that not working! - People would have to be made to still be using that ;D

**Comment by SoulTransfer** [comment]
@bobsta63 - I'm happy to assist your project.
About the IE7, yeah, absolutely correct, its no longer considered supportable as it would require a ot of effort to backport "modern" source code. But i just wanted to make sure that it is "just" not working, and nothing bad happens. (It shows the common jQuery problems but nothing additionally.)
