### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by stevetoza** [sentora/sentora-core#112]
When using the install script : http://sentora.org/install

Getting

Enter the sub-domain you want to access Sentora panel: panel.domain.co.uk
Enter (or confirm) the public IP for this server: 192.xxx.xx.xx

OK: DNS successfully resolves panel.domain.co.uk to 192.xxx.xx.xx

All is ok. Do you want to install Sentora now (y/n)? y
install: line 300: syntax error near unexpected token `>'
install: line 300: `exec > >(tee "$logfile")'

On CentOS 6 and 7

**Comment by bobsta63** [comment]
What OS/Distribution you trying to run it on?

Any chance you had downloaded the installer on a Windows machine and
attempted to make changes to any of the lines before saving and then
attempting to use the installer on a Linux machine? - If so, you'll need to
use something like DOS2Unix before it will work correctly on the server....
We definitely do NOT recommend you making changes the installer though!
