### ISSUE TITLE
i fund this 

### ISSUE THREAD

**Issue by jibswizard** [sentora/sentora-core#113]
http://prntscr.com/621x3u

**Comment by bobsta63** [comment]
We need more information that that I'm afraid eg. what Linux Distribution and version are you running? Where  did you download that install script from?

**Comment by MBlagui** [comment]
Ah ok chattr package missing from your setup we will fix it in the installer.
@5050

**Comment by Caffe1neAdd1ct** [comment]
Issue logged by @MBlagui in installers, closing this issue.
