### ISSUE TITLE
[Feat Req] Create default DNS records on domain join.

### ISSUE THREAD

**Issue by Chewza** [sentora/sentora-core#115]
Wondering if it's possible to add an option to create default DNS entries once a new domain is added to the system.  I know that there are multiple different modules to the way Sentora works, and that the goal is to not have each module dependent on each other.  But if a check could be built into the system to see if the DNS module is active, option to create dns records.

The other possible solution is to create a link in the Domain Success notification when adding a domain which when clicked will create the dns entries for the recently added domain.

**Comment by MBlagui** [comment]
Not any one want auto DNS. It must be either enabled in package setup, so per customer or also server wide like backup.

**Comment by PhilipMcGaw** [comment]
Would also be nice if subdomain information was set up automagically when a subdomain is created.

**Comment by boxbillinggit** [comment]
+1

**Comment by PhilipMcGaw** [comment]
+1

Philip McGaw
www.philipmcgaw.com
07969502077

@Philip_McGaw

**Comment by MBlagui** [comment]
LOL If adding +100 would help guys. Donate to the project and give us a hand ;-).

**Comment by denysvitali** [comment]
Isn't everything into an existent DB table?
Correct me if am I wrong
![schermata del 2015-03-23 20 30 01](https://cloud.githubusercontent.com/assets/4939519/6788674/68799ca6-d19b-11e4-8be6-9b0e47715af9.png)

**Comment by MBlagui** [comment]
All records are created in DB then a hook using a cron job will paste the infos into bind zones.

**Comment by denysvitali** [comment]
@MBlagui If you guys want that I could do it during my free time

**Comment by CasteyDaSilva** [comment]
It should be checkbox option in creating domain/subdomain form to add them automaticly to dns zone/create zone if not exist. Maybe in Sentora config we could set default state (checked/unchecked) for this options?

**Comment by charan315** [comment]
Added auto create dns entries once domain/subdomain created:
Update these files in your sentora:

for Domain: https://github.com/sentora/sentora-core/pull/147/files
for SubDomain: https://github.com/sentora/sentora-core/pull/148/files

**Comment by Caffe1neAdd1ct** [comment]
Instead of editing the subdomain and domain modules it might be worth having a new module with 

AfterDomainCreation
&
AfterSubDomainCreation

Hook files inside a DNS Auto Create module?

This is exactly what the hooks are for... to stop extra functionality bloating the core code and making it hard for us to maintain.

+1 for the feature however this should have been implemented in a new module.

**Comment by MBlagui** [comment]
Agree another module would be nice. Same over creating the DNS in cloudflare instead.

M B

**Comment by TGates71** [comment]
Same as a previous issue which has been bumped up.
