### ISSUE TITLE
MySQL Password Limitations

### ISSUE THREAD

**Issue by Chewza** [sentora/sentora-core#116]
Currently, users are unable to use special characters in their MySQL passwords.

Best practices are Multi-Case, Alpha-Numeric, Special Characters.

I do not see any limitations from MySQL which prohibits the usage of special characters in user passwords.

**Comment by MBlagui** [comment]
supported by mariaDB and should be allowed

@bobsta63

**Comment by Dukecitysolutions** [comment]
Seems to be resolved in MySQL 5.7+. Can not replicate in Sentora v2 with Ubuntu. Need to test with CentOS. Closing for now.
