### ISSUE TITLE
A bug by opening site

### ISSUE THREAD

**Issue by dannyiscool4** [sentora/sentora-core#117]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'u417602285_1.x_settings' doesn't exist' in /home/u417602285/public_html/dryden/db/driver.class.php:176 Stack trace: #0 /home/u417602285/public_html/dryden/db/driver.class.php(176): PDOStatement->execute() #1 /home/u417602285/public_html/dryden/ctrl/options.class.php(29): db_driver->bindQuery('SELECT so_value...', Array) #2 /home/u417602285/public_html/index.php(20): ctrl_options::GetSystemOption('debug_mode') #3 {main} thrown in /home/u417602285/public_html/dryden/db/driver.class.php on line 176

**Comment by dannyiscool4** [comment]
I need help

**Comment by markustenghamn** [comment]
Log into phpmyadmin or whatever you are using to view/manage your mysql databases and check if the table x_settings exists in the database u417602285_1.

Otherwise you will need to add this either from a sql backup or install file. Alternatively you could do a reinstall.

**Comment by bobsta63** [comment]
Not an issue with the core release, appears that you've had a corrupt installation - I'd recommend re-installing - if this doesn't work please re-open this 'issue' and give us the following details:-

* What Linux distrubution and version you are running on your server
* What installer script you are using (a link to the download would be fine)

Cheers,
Bobby
