### ISSUE TITLE
Application Error: [0204] 

### ISSUE THREAD

**Issue by jd1pinoy** [sentora/sentora-core#122]
Always getting this "Application Error: [0204] - The form you attempted to submit had an invalid token!"
when ever I change settings like in Module Admin>>Apache Config>>Force Update
also changing some settings in Sentora Config.

- Sentora 1.0.0 stable release

**Comment by MBlagui** [comment]
What server type? OS used here? Do you have caching like APC? Why you don't open a ticket over this is in forum so we check it?

**Comment by jd1pinoy** [comment]
CentOS here.

After an hour investigation it turns out Zend Optimizer cuases my installation, after removing Zend Optimizer that I've installed it turns back normal.

Please close this.

Thanks MB.

**Comment by MBlagui** [comment]
Yep caching session & code like APC/zend could cause a lot of issues
