### ISSUE TITLE
Wildcard subdomains

### ISSUE THREAD

**Issue by PhilipMcGaw** [sentora/sentora-core#124]
Wild card subdomains are a simple way to set up Wordpress MU and other CMS in a way that allows creation of multiple subdomains.

> http://codex.wordpress.org/Create_A_Network 

the addition of a tick box, or other optional box would be a nice way to create this. all subdomains (in the case of WPMU) just need to point to the domain directory.

**Comment by RickB2000** [comment]
You can do this by adding ServerAlias *.domain.tld to your VirtualHost. And of course an * A record in DNS to your IP.
