### ISSUE TITLE
Auto SSL on all domains

### ISSUE THREAD

**Issue by PhilipMcGaw** [sentora/sentora-core#125]
"Let’s Encrypt is a new Certificate Authority:
It’s free, automated, and open.
Arriving Mid-2015"

> https://letsencrypt.org/
> Could this be looked into as a default for Sentora. - the automatic serving of everything via SSL with no additional set up (easy:https://skippy.org.uk/ssl-on-zpanel-sentora/ - complex:https://skippy.org.uk/more-ssl-on-sentora-zpanel/) would be a huge selling point for this Panel application.

Also the automatic enrolment of the panel address would be a good security move.

**Comment by apintocr** [comment]
I agree with this.
However doesn't this fall into an optional module?
Either way it's a great idea :+1:

**Comment by 5050** [comment]
yes. As many, I have proposed (from long time ) the idea of an independent module to handle and configure ssl, but there are a lot of people to report and not enough to develop ! 
I'm curently out of sentora : overloaded with job. But it is written in team tablets.

**Comment by JonathanNet** [comment]
Yeah would be nice with support for letsencrypt :)

**Comment by m0k1** [comment]
I will tommorow finish writing my addon for "AutoSSL".
There will be 3 main function's.
AutoSSL of all domains in panel
AutoSSL of all future domains added to panel.
Redirect http to be serverd only from https :+1: 


hmmm, https only sentora :3

**Comment by tfohlmeister** [comment]
@m0k1 Sounds great, thanks for your efforts! Where can I find your addon?

**Comment by csong95** [comment]
Is anyone still working on this ?

**Comment by Ron-e** [comment]
https://github.com/TGates71/sencrypt

**Comment by TGates71** [comment]
Sencrypt module will be a core module in v2.0.1 if all goes well.
