### ISSUE TITLE
Welcome E-mail - Billing

### ISSUE THREAD

**Issue by rafaht** [sentora/sentora-core#126]
Currently, the welcome e-mail haven't a possibility of change at the Sentora Panel, only it's possible changing a file at the modules directory. Every time that a update is released, this modification will be lost.
Is interesting  a possibility of change the content of this message at the panel, without modifying the panel files.

**Comment by jacobg830** [comment]
+1 :+1: 

Shouldn't be too difficult to implement either :)

**Comment by TGates71** [comment]
I think this was mentioned a while back, to move it to the database instead of inside the module.

**Comment by TGates71** [comment]
Bump for review

**Comment by TGates71** [comment]
Added a long time ago.
