### ISSUE TITLE
[Feat Req] PTR Record

### ISSUE THREAD

**Issue by michal-sapsa** [sentora/sentora-core#135]
Other solution like ispconfig got this.
Would be great to be able to use it.

This is realy important for people using mail servers and don't want to fall in spam hell

**Comment by CasteyDaSilva** [comment]
PTR record have to be set by ip address provider, not website hosting.

**Comment by michal-sapsa** [comment]
Why not add support, like ISPConfig did

**Comment by CasteyDaSilva** [comment]
because it will not work, PTR have to be set by IP owner.
If you want to set own PTR record, you should contact with IP address owner.

**Comment by denysvitali** [comment]
As @CasteyDaSilva PTR records should be setted by the IP owner. You couldn't do it by your own.

**Comment by michal-sapsa** [comment]
Strange - I can setup it in ISPconfig, and OVH allow me to do that ...
If im buying IP address from OVH then im the owner...
Oh and it Works allright...

**Comment by denysvitali** [comment]
The point is that you couldn't change the public ip of your machine from itself.
It should be do by your provider, hence they are the ones who set your RDNS
