### ISSUE TITLE
Typo on Sentora logo - "hositng' instead of "hosting" on slogan

### ISSUE THREAD

**Issue by pankajpragma** [sentora/sentora-core#138]
Hi,

I am using Sentora and it is very impressive.
When we setup new account/website then it shows default page (index.html).

I can see a typo on its logo. Slogan says "hositng' instead of "hosting".
Screenshot: http://screenpresso.com/=HqbP

It's not a bug but you may like to correct it.

Thanks for providing great open source solution to manage hosting.

**Comment by Ron-e** [comment]
LOL, this was already changed in the art but not jet included in the core.. 
https://github.com/sentora/art/commit/33da1ac1e7a977b04b03c9a1a4349601bd6e04f3

**Comment by bobsta63** [comment]
Updated logo has been merged to 'master' - closing this issue.
