### ISSUE TITLE
Install sentora on port not subdomain

### ISSUE THREAD

**Issue by MoBadawy** [sentora/sentora-core#140]
Why sentora does't setup on port like this http://xxx.xxx.xxx.xxx:xxxx instead of subdomain ?

**Comment by 5050** [comment]
was a choice before sentora... and it is like colors : some prefers one, other another.
The perfect would be a question on setup to choose between both.

**Comment by bobsta63** [comment]
I also feel that it's a better solution as most corporate firewalls and
proxies restrict non-stanard HTTP/HTTPS ports... just a thoguht :)

**Comment by CasteyDaSilva** [comment]
I think, question about prefered access url at setup will be good, but @bobsta63 have right, non-standard port can be a problem.

**Comment by michelsup** [comment]
Also, working with subdomains is the easiest way to split services between different hardware servers.

**Comment by RickB2000** [comment]
You are currently able to set this up? Why don't we close this issue?

**Comment by 5050** [comment]
It acts as remainder. It is not urgent, but when I could be back on the installer or on the apache manager, I'will try to see if there is a simple way to implement a choice.

**Comment by Caffe1neAdd1ct** [comment]
There are separate ports in x_settings for the control panel vs virtual hosts so this would be quite simple to implement.

**Comment by TGates71** [comment]
It can be on custom port. but it is NOT suggested to be run or accessed using IP! This is why there is a question during install for you to set the login subdomain. Check any other hosting software too, they suggest subdomain.domain.com:port.
