### ISSUE TITLE
mysqld takes 400M memory

### ISSUE THREAD

**Issue by MoBadawy** [sentora/sentora-core#141]
I have a problem with mysql it using a lot of memory how to optimize it?
BTW there is a problem with forum Registration

**Comment by michelsup** [comment]
One of mine takes 28GB, so 400M doesn't mean much. It all depends on your hardware specs. BTW you can have a look to http://mysqltuner.com/ for obvious tips. I as well use https://www.mysql.fr/products/workbench/ to get an overall look to my server performance.

**Comment by Caffe1neAdd1ct** [comment]
MySQL can take a lot of memory, just be thankful it's not oracle ! 

I would suggest the minimum ram for a full stack installation like sentora should be > 1GB however i have had installations running smoothly with 512MB before.
