### ISSUE TITLE
[Feat Req] Add "wget" in cron

### ISSUE THREAD

**Issue by k-andrew** [sentora/sentora-core#142]
For Example:
Script: _http://example.com/cron.php_
Run _wget http://example.com/cron.php >/dev/null_

**Comment by Caffe1neAdd1ct** [comment]
crons are restricted using php blacklist functions and openbase_dir to restrict file access to user's own directories inside `/var/sentora/hostdata/username/*`

I would suggest using the php script to download the file using curl/http/file_get_content etc.

We would be reluctant to open up this sort of functionality.
