### ISSUE TITLE
No postmaster email adress created by default

### ISSUE THREAD

**Issue by michelsup** [sentora/sentora-core#143]
When you create a domain in sentora, it creates it with a MX record.
Per RCF1123, 5.2.7 RCPT Command : "A host that supports a receiver-SMTP MUST support the reserved mailbox "Postmaster"
Some DNS do reject updates when the domain do not comply with RFCs.
It would be great to implement an automation correcting this issue.

**Comment by TGates71** [comment]
Also, abuse@ and webmaster@ should be included for that matter. But, automation is second thought as when manually created you create the passwords to your choice....

**Comment by PhilipMcGaw** [comment]
Creating them with an unknown password is not an issue and have them all drop into the postmaster mailbox. 

Then it is up to the user to either reset the password, ignore them all, or forward them into another account.

Philip McGaw
www.philipmcgaw.com
07969502077

@Philip_McGaw

**Comment by michelsup** [comment]
Are these two mandatory regarding DNS RFCs ? I thought they were for webservers only.
https://www.ietf.org/rfc/rfc2142.txt
I think we can use the account password for the postmaster email, with a reminder somewhere in the mailboxes page.

**Comment by ryucz** [comment]
Maybee these accounts should be redirected to server admin, instead of user itself.

**Comment by CasteyDaSilva** [comment]
Creating mailbox postmaster could add passowrd to password.txt like a mysql root passwords.

**Comment by michelsup** [comment]
@ryucz It's up to the owner to take care of the husbandry of his site/domain.
@CasteyDaSilva Good idea.

**Comment by TGates71** [comment]
As stated above, the server owner/manager is responsible for correctly setting this up. Also, some servers may not have the email module enabled (depending on the server's purpose) and auto-creation will fail.
