### ISSUE TITLE
Mysql users with sentora user prefix

### ISSUE THREAD

**Issue by CasteyDaSilva** [sentora/sentora-core#145]
I think, mysql users needs to change format to sentorauser_mysqluser. 
Example: testuser_user
It will allow to create users similar mysql user by many users without notify about existing mysql user.

**Comment by ryucz** [comment]
+1 This could be useful

**Comment by Chewza** [comment]
+1 user naming should be consistent throughout the different modules of the panel.

**Comment by denysvitali** [comment]
+1 doing this will prevent creation of databases with strange names

**Comment by RickB2000** [comment]
I have made this reality. Pull request is sent. Waiting for acceptation.
