### ISSUE TITLE
I am making a Wiki for how to Run Ruby on Rails app with Phusion Passenger in Sentora.

### ISSUE THREAD

**Issue by gavargas22** [sentora/sentora-core#150]
@jacobg830 Hello there!, I wanted to ask if it was ok for me, (I actually already got started) making a Wiki for how to run a RoR app in Sentora. Was that the correct way of doing it?

**Comment by gavargas22** [comment]
Here is the link for quick access:

https://github.com/sentora/sentora-core/wiki/Running-a-Ruby-on-Rails-App-in-Sentora-with-Phusion-Passenger

**Comment by apintocr** [comment]
This is great!
I also checked Passenger a while back and it seemed a good way to implement ruby on Sentora.
Take care with security because it is easy to make flaws.

**Comment by gavargas22** [comment]
Ok, I added some more stuff to the Wiki, if possible, when I am finished, (I'll let you know) and could you check my setup for any potential problems?
