### ISSUE TITLE
password reset form field is text

### ISSUE THREAD

**Issue by khanals** [sentora/sentora-core#156]
when we forgot password and after clicking it shows text field. how to change to password field

**Comment by TGates71** [comment]
Not sure where you are referring to (what file) but the general change would be to change the input 'type' from "text' to "password" like below:
```
<input type="text" name="password">
```
To:
```
<input type="password" name="password">
```

**Comment by Ron-e** [comment]
Do you mean where you need to fill in your email address so you get a new password?

**Comment by Caffe1neAdd1ct** [comment]
Looking into this for the next release.
