### ISSUE TITLE
Disabled clients

### ISSUE THREAD

**Issue by k-andrew** [sentora/sentora-core#166]
Do disabled clients continue to work website

**Comment by RickB2000** [comment]
How do you mean? If you are more clear I can try to create it :)

**Comment by k-andrew** [comment]
After disabling the client continues to work his site.

**Comment by Caffe1neAdd1ct** [comment]
Disable client websites on client disable, we could have a setting which allows them to keep working or disables on the next daemon run.

**Comment by Dukecitysolutions** [comment]
By default disabling a client in Sentora only stops them from panel access. Clients site will remain active. Sentora has a setting in configs to fully disable user vhost and render access to site as well. Closing for now.
