### ISSUE TITLE
Adding new Subdomains and Emails should verify if the user is the owner of that domain.

### ISSUE THREAD

**Issue by apintocr** [sentora/sentora-core#172]
As pointed on the forums:
http://forums.sentora.org/showthread.php?tid=1680&pid=10796

**Comment by iammeat** [comment]
Hi.  No other control panel in existence performs this kind of sanity check.  It's too hard to confirm the information.

For example, what if the person in question has privacy on their domain, and the domain is owned by "godaddy.com"?

**Comment by eByte23** [comment]
You don't understand that verification in which is being discussed this is for a user that has added a domain user create manipulate the dropboxes change the value thus allowing them to change what inputs into the data base allowing them to send other peoples emails to them or create a sub domain of someone elses domain under their account.

**Comment by bobsta63** [comment]
Yeah i agree, trash this FR!

There are also instances where you may be hosting the site on behalf of the domain owner.

Just my two cents worth :)

~ballen

**Comment by eByte23** [comment]
From memory when I did testing the other day Mailboxes,forwarders,aliases,subdomains and dns modules needed to be fixed. Dns one wasn't to bad but i still was able to get further than I should have been able to.

**Comment by bobsta63** [comment]
Hi Elijah,

Unless the code had been removed recently, That verification already exists in Sentora as you can only add mailboxes for domains you've added to the server anyway.

Hope this helps,
Bobby

**Comment by eByte23** [comment]
Hi Bobby,

I'll test again but i am pretty sure that when I did it the other day I was able to add someone@example.com by do manipulation and asub.example.com as sub domain etc. with out example.com registered in sentora.

re checking now....
Elijah

**Comment by eByte23** [comment]
Confirmed.
Created user someone@example.com and logged into webmail

**Comment by bobsta63** [comment]
Righto, yeah that needs looking at then... Good find!

**Comment by eByte23** [comment]
Yep sure does...Yeah I'll do them now while I'm going.

**Comment by eByte23** [comment]
@5050 @motters @Caffe1neAdd1ct @TGates71

**Comment by apintocr** [comment]
This has SERIOUS implications and should be marked as critical.

**Comment by eByte23** [comment]
? this has been merged now. What do you mean?

**Comment by apintocr** [comment]
This also works on FTP with all the issues that brings...
I'm working on a HotFix for this.

**Comment by eByte23** [comment]
Yeah that module needs some work. It has issues.
