### ISSUE TITLE
Domain Names 

### ISSUE THREAD

**Issue by tawhid111** [sentora/sentora-core#175]
If i assign a " domain name"  to Client  A for instance:  example.com 
Then i delete the Client A Account completely..
Later i try and  assign example.com to Another Account to for instance a New Client B account.

I get the Following error : 

The domain already appears to exist on this server.

**Comment by TGates71** [comment]
Correct. Sentora saves all past info but marks it 'as deleted'. Please check my post on the forums, module section, for my new module 'deleted records manager'.

**Comment by tawhid111** [comment]
Tgates Thanks for the reply 
deleted records manager is a great tool
i already have your module installed but it does not have "deleted domains" can you maybe include it or tell me how can i manually fix it ?

**Comment by TGates71** [comment]
As per BOTH of your other posts in our forums, Use the Vhosts tab and the DNS tab and remove all records for the domain.
