### ISSUE TITLE
Require all granted for Order Allow,Deny on apache 2.4.10 / Error 403 - Access Forbidden

### ISSUE THREAD

**Issue by hardlick** [sentora/sentora-core#180]
Error 403 - Access Forbidden

There is a problem with sentora on apache 2.4.10,  vhost for default add :
 Order Allow,Deny...
but this is deprecate, now the sintax is:
Require all granted 
i changed manually the file vhost but after some time the file load the default setting, 
help please!

**Comment by MBlagui** [comment]
we don't suypport ubuntu 15.04 or plan to do so currently.

Check the forum for the solution.

M B

**Comment by kkprince1998** [comment]
Just saying, shouldn't we start adapting this new configuration, to  make it easier to upgrade to the next LTS release when it comes out? I could invest some of my time to reconfigure this. Does sentora still support pre 14.04 versions?

**Comment by MBlagui** [comment]
1. use the forum.

2. installer support 12.04 & 14.04. And no issue to support any change in apache in future once it's an LTS. We will do as we did already with the upgrade to 14.04.

M B

Thanks issue can be closed @TGates71

**Comment by kkprince1998** [comment]
Ah ok. Just gonna say that the forum ain't working for me so I can't use it.

**Comment by MBlagui** [comment]
Sorry the forum works fine and we are doing our best to answer all questions.

I already answered and pointed your made a mistake forcing install as 12.04. This is not an issue on our side.

M B

**Comment by kkprince1998** [comment]
> Sorry the forum works fine and we are doing our best to answer all questions.

I haven't received the activation email, meaning i can't post. I've tried two emails with no success, and there isn't anything in my spam folder.


> I already answered and pointed your made a mistake forcing install as 12.04

When did I do this?

**Comment by TGates71** [comment]
What email/username combo did you use? I will manually activate it for you.

**Comment by kkprince1998** [comment]
kkprince, and the email is either kaiden_prince@Linuxmail.org or kkp12345@mail.com.

**Comment by hardlick** [comment]
Hi i resolved the problem, update the install!..... on the part: if ubuntu release is: 12.04, or 14.04, i changed to 15.04 and works fine!...
the fixed is not difficult, so i suppose you can update the install!

**Comment by TGates71** [comment]
Account with kaiden_prince@linuxmail.org activated. @kkprince1998

**Comment by kkprince1998** [comment]
Thanks @TGates71. Mind if you remove my email from your comment?

**Comment by Caffe1neAdd1ct** [comment]
If i remember correctly CentOS 7 supports this setup, please raise another issue if this hasn't been sorted for Ubuntu servers and we can have a look when time permits.
