### ISSUE TITLE
DNS records not updating, and apache config also.

### ISSUE THREAD

**Issue by djbeater** [sentora/sentora-core#181]
#### Hello, thanks for great project

Yesterday i make new dns cname record old.utils.gradio.lv from DNS manager, but today still not reachable from dig command

My Server is Ubuntu Linux 14.04.2

The weird thing is that, when ir go to webmin panel BIND DNS Server and look for all records in that zone i see that new record shows up, but from dig not, also tried @my-server-ip like internal request, also nothing appears, but if i press Apply zone from webmin BIND DNS Server for particular gradio.lv zone, the momentary i can dig new DNS record.

Also i got observations, that with apache are the same, if i make some changes, they not get apply till i press Apply changes in webmin Apache Webserver.

**Comment by kkprince1998** [comment]
Did you configure you registrar to use your server's DNS? You have to have two IPs on your server and two domains.

The first domain gets configured with your registrar's DNS, and must have 2 A records, each pointing to each of your two ips. It doesn't matter the sub domains you choose, but traditionaly you would use ns1 and ns2, and I will assume you used these from now on.

Then on your second domain you go to your registrar and look for something like 'use your own DNS/name servers'. Go to it and it will ask which name servers you want, just put in ns1.(your first domain).TLD in the first and the same in the second, except with ns2. Wait up to 72 hrs and it should be using your sentora DNS.

**Comment by kkprince1998** [comment]
As for your second issue, could you elaborate a bit mor please?

**Comment by djbeater** [comment]
Yes my DNS all works fine, if i reload, from my terminal eg:
```bash
rndc reload gradio.lv
```
then DNS applies and i can dig my newly created subdomain.

For second issue, for example i add DocumentRoot in Override a Virtual Host Setting then click save, then check Force Update and click save, wait for next daemon run, but after my changed document root not applies, but if i execute command:
```bash
sudo service apache2 reload
```
Then my new apache settings aplies.

Hopes that now get lil bit clearer.

**Comment by eByte23** [comment]
For the second part of what was said about the apache reload. That could be a bug that for some reason the apache reload flag hasn't been set. In my experience even if you to force reload it doesn't reload unless that flag on set.

**Comment by Caffe1neAdd1ct** [comment]
Please raise an issue on forums.sentora.org for support with this issue. 

I would suggest to check the sentora logs in `/var/sentora/logs` to see if the daemon is actually running and restarting the services correctly (if it detects a change has been made).
