### ISSUE TITLE
All modules goes off, on module edit refresh or click link .

### ISSUE THREAD

**Issue by dansanti** [sentora/sentora-core#182]
HI ! well , when yo for some reason refresh or on url  bar  you make an enter, in this link http://panel.domain.tld/?module=moduleadmin&action=EditModule all modules goes off, and the only way to recover it, is with mysqlworkbench (or another tools) and manually add groups to modules

Sorry for my bad english, but i think this issue must be solved.

Thanks..

**Comment by dansanti** [comment]
x_permissions also was removed

**Comment by Caffe1neAdd1ct** [comment]
Thanks for the bug report, will be looked at for the next release.

**Comment by TGates71** [comment]
Resolved? Still an issue?

**Comment by TGates71** [comment]
Haven't had any reports of this happening over the past few years.
