### ISSUE TITLE
Domain Management Tab

### ISSUE THREAD

**Issue by michal-sapsa** [sentora/sentora-core#186]
When you edit domain via domain management and want to go back to selecting domain to load in domain management editor and you click top bar
[ Home > Domain Management > DNS Manager ] on 'domain Management' 
instead going (?module=dns_manager) it gose to main page (#domain-management)

**Comment by eByte23** [comment]
It does that got every thing.

**Comment by Ron-e** [comment]
I think that you used the breadcrumbs (this is not the navigation bar), this is suppose to do that.

**Comment by michal-sapsa** [comment]
it maybe "breadcrumbs" but they should work like "go back". Because there is no point for clicking "Domain Management" just to go on home panel.
Othere "breadcrumbs" work same as Domain Management, which is in my opinion incorrect.

**Comment by michal-sapsa** [comment]
I see it just send you back and bold the container of Domain Management... so probably that intended
