### ISSUE TITLE
Adding domain records via DNS Manager - can't add different type record of same domain

### ISSUE THREAD

**Issue by bigretromike** [sentora/sentora-core#187]
When adding A record for 'test'
you are unable to add TXT, SPF type of record for 'test' because it scream about 'Hostnames must be unique'

Which is invalid because it should check if record is unique for its kind

WORKAROUND till fix: 
adding record by had sentora_core.x_dns;

**Comment by Caffe1neAdd1ct** [comment]
Thanks for reporting will be looked at for the next release.

**Comment by Dukecitysolutions** [comment]
This should have been fixed in v.2.0.0. (Ubuntu 18.04/20.04-CentOS 8) support. It was a issue with dns bind version on OS that didn’t support that at the time.
