### ISSUE TITLE
Module FTP Management Allows any user to delete and change passwords of any account.

### ISSUE THREAD

**Issue by apintocr** [sentora/sentora-core#191]
By manipulating the data sent to the server a user can DELETE and RESET PASSWORD of any FTP account.
Also, it is possible to find valid logins by issuing queries to sequential IDs.

Initially reported by @eByte23 on #189 
+1 for @Caffe1neAdd1ct

**Comment by RickB2000** [comment]
I suggest we close the issue? Because it's fixed...
