### ISSUE TITLE
Critical Error: [0100] - Unable to connect or authenticate to the Sentora database (sentora_core).

### ISSUE THREAD

**Issue by baulahakaji** [sentora/sentora-core#193]
I got this error in my panel... I cannot connect to the database... I don't know how this error came....
{
Critical Error: [0100] - Unable to connect or authenticate to the Sentora database (sentora_core).
We advice that you contact the server administrator to ensure that the database server is online and that the correct connection parameters are being used.
}

**Comment by eByte23** [comment]
If you have come line access if running Linux try MySQL -u {user} -p 

Should prompt for password.

If this connects Db server is running.
If running Ubuntu try /etc/init.d/mysqld restart

**Comment by TGates71** [comment]
Github is not for support. Please use our forums here: http://forums.sentora.org/
Thanks!
