### ISSUE TITLE
Wrong time for Deamon in Server Status page (under Advanced)

### ISSUE THREAD

**Issue by cloud1250x4** [sentora/sentora-core#200]
In Advanced>Server Status
http://puu.sh/kkwhn/075430094f.png

In Sentora Config 
http://puu.sh/kkwqq/017d3f6635.png

**Comment by Caffe1neAdd1ct** [comment]
Did you install using master branch or 1.0.3 tag?

**Comment by cloud1250000** [comment]
I used the installer script available on your website

**Comment by Caffe1neAdd1ct** [comment]
It may be the daemon is using or forcing UTC or something similar..

What is your server timezone set as?

**Comment by TGates71** [comment]
Works in v2
