### ISSUE TITLE
WebMail not working.

### ISSUE THREAD

**Issue by VizionStudios** [sentora/sentora-core#202]
Each time I go to my email it does not have the emails sometimes.
http://prntscr.com/8kcp9d

**Comment by Caffe1neAdd1ct** [comment]
Are there any errors generated in the roundcube logs or dovecot logs when accessing them?

Use `tail -f` on the logs files while loading roundcube and let us know of any errors.

**Comment by MBlagui** [comment]
Use the forum for this issue. I don't think this is a bug.

OS? Configuration? Any custom setup for mail server? We need all that so we can try to reproduce it or track it's origin.

M B

**Comment by xabixab** [comment]
Do you have POP3 configured in other mail client (Gmail, thunderbird...)?

**Comment by MBlagui** [comment]
Round cube issue. To solve it long on MySQL/PhpMyAdmin. Check sentora_rouncube and get users table, delete the User settings, and log again it will be fixed. Also removing the field custom setting will solve it (I don't remember the exact field).

Closing it. Will see if it persists when we upgrade round cube.
