### ISSUE TITLE
Domain Management on Ubuntu14 VPS (DigitalOcean.com)

### ISSUE THREAD

**Issue by cliqtoni** [sentora/sentora-core#204]
I find that when you performed operations such as creating a domain and setting its DNS records or sub-domain, the operation is not automatically effected on the VPS. I have to login to the VPS panel to create the domain and DNS.

Also created domsins/accounts do not appear on the list when logged in buy a higher lever user.
Eg. Admin does not see domains created buy resellers or by users unless he uses shadow

**Comment by TGates71** [comment]
Sentora is not made to control your VPS.

That is correct. But a module could be made to do such a task (View all domains/sub domains of inherited resellers and users) or use the zGodx module > Virtual Hosts (Shows a list of all domains/sub domains on your server.)

**Comment by cliqtoni** [comment]
Okay thanks.
If you would be kind to explain how www.mach-hosting.com attempts to solve this VPS Domain/DNS auto creation problem.

Does he have to manually do so for every domain he host and every domain hosted my clients in his    reseller and user accounts?

Thanks.

**Comment by eByte23** [comment]
There would be a few different ways this could be achieved, he is more than likely using a billing module from somewhere which may offer hooks on client creation of domain and package type to auto create dns. Or he may use the standard on domain creation hook to execute then dns creation.

**Comment by TGates71** [comment]
That's my hosting ;) I do not use a VPS but an actual home server running Sentora's DNS.
All DNS is done inside Sentora. Addon domains point to my nameservers from my registar, my nameservers point to my server's IP.
More info here: http://docs.sentora.org/?node=95

**Comment by cliqtoni** [comment]
Thanks @TGates71 
Can I run my DNS using Sentora's DNS while running a VPS?

**Comment by eByte23** [comment]
Yes, I do that. 

I don't actually use sentora for client hosting at the moment just use it for my dns,email and few sites

I have 2 vps with sentora and just have dns records in both ns1,ns2

**Comment by TGates71** [comment]
I suggest you visit the forums for more support on this. We have a lot of community members who use Digital Ocean VPS services ;)
http://forums.sentora.org
