### ISSUE TITLE
DNS on Ubuntu14 VPS (DigitalOcean.com) 

### ISSUE THREAD

**Issue by cliqtoni** [sentora/sentora-core#205]
DNS record set directly on the VPS is not read/written/deleted on the Sentora Panel.
Sentora just creates displays its own with no link to the DNS settings on the VPS

**Comment by TGates71** [comment]
Correct. Either you use Sentora DNS or your VPS, not both.

**Comment by cliqtoni** [comment]
But Sentora DNS does not work when used. Is it the VPS? or Did I break something?
I'm pretty sure I didn't because I have tested twice and followed every step carefully and experienced no errors.
