### ISSUE TITLE
User's Email Retained After Deletion

### ISSUE THREAD

**Issue by cliqtoni** [sentora/sentora-core#206]
Once a user account is deleted, his email address is retained.

You cannot create a new user or recreate user with previous email address. An error is displayed indicating the email already exist or is associated with another user

**Comment by TGates71** [comment]
There are 100's of posts with answers to this on our forums: http://forums.sentora.org
Also read here: https://github.com/sentora/sentora-core/issues/68
Check forums for Deleted records manager.
