### ISSUE TITLE
SMTP Password field is wrong type.

### ISSUE THREAD

**Issue by ghost** [sentora/sentora-core#208]
SMTP Pass field is textarea instead of input with password type.

Change:

```
<textarea cols="30" rows="1" name="smtp_password"></textarea>
```

To:

```
<input type="password" name="smtp_password" placeholder="Type your smtp password here">
```

**Comment by TGates71** [comment]
Unfortunately, due to the way it is coded and the way it renders the input lines from the database, it cannot be changed in the manner you describe. Will look into it some more.

**Comment by TGates71** [comment]
In this file: https://github.com/sentora/sentora-core/blob/master/modules/sentoraconfig/code/controller.ext.php
Between line 51 and 52 add:
```				if (strpos(ctrl_options::OutputSettingTextArea($rowsettings['so_name_vc']),'smtp_password') !== false) {
					$fieldhtml = '<input type="password" name="smtp_password" value="'.$rowsettings['so_value_tx'].'">';
				}```

**Comment by Dukecitysolutions** [comment]
@TGates71 , @MBlagui , 
Any updates on this?

**Comment by TGates71** [comment]
Was completed 9 years ago.
