### ISSUE TITLE
A few enhancement?

### ISSUE THREAD

**Issue by NegativeIQ** [sentora/sentora-core#209]
Just installed Sentora and i love it. Well i have to love it after manually managing everything with nano editor for half year

Anyway here are few things i think should be improved.

DNS Records are created automatically for each domain but only when you enter dns manager. Why not generate them the moment new domain is created? (Or at least add it as option in admin config)

Also when creating subdomain, it only has two options for home dir. Existing one and to create new. While new one can be useful in some cases, usually when you are creating subdomain you want it to be inside domain home dir. So how about adding option to create new home dir but inside existing home dir, and/or even better relative to existing one?

And how about adding option to automaticaly create ftp user when we create new domain? Usually its what we need

And from technical side, i noticed that passwords are stored inside mysql table without any kind of hash...At least for FTP users...That is pretty risky from security point of view...

**Comment by Ron-e** [comment]
have you searched the forums? -> http://forums.sentora.org/
most questions are answered multiple times..

**Comment by NegativeIQ** [comment]
Please dont just read title and come to conclusion, specially when someone tries to write a proper post.
If you would actually read my post you would notice its not a question, its a suggestion(s).

**Comment by eByte23** [comment]
Hi @NegativeIQ,

Don't worry @Ron-e was just suggesting to view the forum, as a lot of other people have done exactly your suggestions before and it would be on the forums, the forums also have the dev section where these issue/features could be talked about.

Anyway I agree with many of your points, if would like these enhancements put them in as separate issues, and that will be give them the best chance of being put into the product directly.

As for the FTP users passwords yes they could be store a bit better e.g. encrypted.
But I believe this also links to the actually proftpd config so I am unsure if this could be encrypted.

Elijah :)

**Comment by TGates71** [comment]
Correct Elijah, it's the way that proftpd stores them :( has asked and has been investigated before.

**Comment by eByte23** [comment]
A little hard to read but i think it could be possible to do this.

http://marc.info/?l=proftpd-users&m=115786019409666
http://www.proftpd.org/docs/contrib/mod_sql_passwd.html#SQLPasswordOptions

That was on a quick search but I would say it seems possible

**Comment by TGates71** [comment]
Ok. We'll take a look at it. Thanks.

**Comment by MBlagui** [comment]
It could be enhanced later. Tagging it for 1.1 and closing it.
