### ISSUE TITLE
[Feat Req]Easy reseller branding

### ISSUE THREAD

**Issue by CasteyDaSilva** [sentora/sentora-core#211]
In my opinion, resellers needs to have options to brand panel for themselves. I mean several quite simple options:
- Set own logo and panel title without installing separate theme.
- Set available modules (now, if we activate module admin for resellers, they can change administrator settings etc.).
- Set own FAQ (now they cannot remove default questions).
- Set own default DNS records.

**Comment by MBlagui** [comment]
We should change the templating engine first...
