### ISSUE TITLE
[Feat Req] Logrotate

### ISSUE THREAD

**Issue by CasteyDaSilva** [sentora/sentora-core#212]
Domain logs (error and access) can easily eat space from server. It could be minimized easily by using of logrotate. Logrotate should be installed and configured by default. Maybe with possibility to change settings in panel (rotating by time or file size etc.)?

**Comment by bbspike** [comment]
you can find the scripts for Sentora logs here:

http://forums.sentora.org/showthread.php?tid=2211&pid=13795#pid13795

**Comment by Dukecitysolutions** [comment]
We have added this to v2. We will be working on testing and making sure logrorate works correctly with Sentora logs and uses the correct permissions.
