### ISSUE TITLE
mySQL username prefix to long

### ISSUE THREAD

**Issue by bbspike** [sentora/sentora-core#225]
A client of mine had a username weddingplannerdelal. This username is used as prefix for mysql user like weddingplannerdelal_. It seems that this prefix is to long, because there are error's when making a new mysql user. Sentora gives "wrong username"

After i changed the username from weddingplannerdelal to delal the issue was solved.
https://github.com/sentora/sentora-core/pull/226

**Comment by bbspike** [comment]
No comments?:)

**Comment by eByte23** [comment]
Use PostgreSQL you 64 char length for usernane

**Comment by MBlagui** [comment]
Fixed
