### ISSUE TITLE
Forbidden error when downloading backups

### ISSUE THREAD

**Issue by jacobgelling** [sentora/sentora-core#233]
Forbidden error is displayed when downloading a backup. Reproduce by:
- Going to Advanced -> Backups
- Press ```Launch``` button
- Press ```Backup Now``` button
- Press ```Download Now``` button

I presume this is because of changes to htaccess.

This also creates a file that is never deleted in the etc/tmp directory, related to #232?

**Comment by TGates71** [comment]
Refer to #232

**Comment by MBlagui** [comment]
Manual download should be removed to avoid confusion until the module get totally reworked.
