### ISSUE TITLE
Permanently High CPU Load

### ISSUE THREAD

**Issue by Serbmusic** [sentora/sentora-core#243]
Hello,

I want to ask if this is normal ?  Before I understand this case I reboot the server because all 16 cores had been 100% usage. After the reboot the situation is this:

![image](https://cloud.githubusercontent.com/assets/16796592/12446709/435821a0-bf74-11e5-9878-fb6629329e26.png)

Thank you in advance for your assistance.
Best regards,
Nikolai.

**Comment by Caffe1neAdd1ct** [comment]
Basically the daemon process is starting to overlap due to being very long running on your server.

I would suggest editing the crontab for apache and increasing the time between daemon runs.

**Comment by Caffe1neAdd1ct** [comment]
As i haven't got a sentora install handy, looking in the installer i can see the following lines:

```
sed -i "s|!USER!|root|" "$PANEL_CONF/cron/zdaemon"
cp "$PANEL_CONF/cron/zdaemon" /etc/cron.d/zdaemon
chmod 644 /etc/cron.d/zdaemon
```

So you should be able to edit /etc/cron.d/zdaemon 

Then restart crond service.

**Comment by Caffe1neAdd1ct** [comment]
Oh for information purposes, the daemon is set by default to run ever 5 minutes.

Webalizer task is normally one of the longer running tasks, so you could look into disabling this task's daemon hook if you aren't worried about website status module.

**Comment by Serbmusic** [comment]
Thank you about the fast answers !
Here you are my /etc/cron.d/zdaemon file:

SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
HOME=/
*/5 * * * * root nice -2 /usr/bin/php -q /etc/sentora/panel/bin/daemon.php > /var/sentora/logs/daemon-last-run.log 2>&1

The interesting is that the daemon.php is working permanently despite this in crontab.
What will be changed if this daemon job be deleted from crontab ?

Thank you !

**Comment by Caffe1neAdd1ct** [comment]
Website stats won't generate
Domains/Subdomains won't go "live" when created without manually running this job
DNS changes won't go live
and a few other bits (this is from memory at the moment)

I would change the cron to run every hour or 30mins:
```
*/30 * * * * root nice -2 /usr/bin/php -q /etc/sentora/panel/bin/daemon.php > /var/sentora/logs/daemon-last-run.log 2>&1
```
or
```
1 * * * * root nice -2 /usr/bin/php -q /etc/sentora/panel/bin/daemon.php > /var/sentora/logs/daemon-last-run.log 2>&1
```

This process needs to run for certain panel actions to be put into config files and for the related services to be reloaded.

**Comment by bobsta63** [comment]
That'll probably be the fact that the previous instance just hasn't finished... So just looks like it's running "forever".

Try to "kill" the process and watch "top" and see how long before it restarts... Should restart within 5 mins and then that'll prove its working on the crontab..

**Comment by Serbmusic** [comment]
Great, I kill the process and now I realize, the problem is that the process for some reasons didn't end because after 5min starts again... and another 5min starts again... now I made edit /etc/cron.d/zdaemon with:
1 * * * * root nice -2 /usr/bin/php -q /etc/sentora/panel/bin/daemon.php > /var/sentora/logs/daemon-last-run.log 2>&1

and restarted crond. I hope the problem will be solved.

**Comment by Caffe1neAdd1ct** [comment]
I would advise to run the daemon manually and record how long it actually
takes just to make sure, 1h should be plenty though.

**Comment by Serbmusic** [comment]
Yeah 1h is perfect... the process works between 15-25m. if the server is not overloaded. Now the machine and cpu are relaxing ;). Thanks about your great and fast assistance.

Best regards,
Nikolai.

**Comment by TGates71** [comment]
15-25min? WOW! @Serbmusic  How many sites/clients do you have?

**Comment by MBlagui** [comment]
I think this is more related to daemon. Do you have backup enabled?

I think we will improve backup module and add a failsafe that will tell backup don't run AGAIN For the next hour as a new backup is already in the pipe. This will avoid the double backup issues and getting CPU use spikes.

May be we could even set the safe timing for backups ( in the night we servers are ok).

**Comment by TGates71** [comment]
I have already fixed the backup module.
Related:
https://github.com/sentora/sentora-core/commit/93ef98115da2393c9c7c2aa7d4a19cdec1d5f9e8
https://github.com/sentora/sentora-core/commit/9d55dc1ca2713f04851867d9522bd6ff36d88511

**Comment by MBlagui** [comment]
backup need more fixes.
Thinking about adding a fail safe so it won't no more get the duplicated backups. 
Adding SQL/HTML separated zip. A lot of features.

**Comment by TGates71** [comment]
Duplicate backups no longer occur with the fix. I have been running it successfully for the past 4 months and it works just as it should. Makes a new backup every night and removes the oldest. The manual backup is what needs improvement. For manual backup it should pretty much do the same as the auto backup except with one click to create it and possible d/l link.

**Comment by MBlagui** [comment]
@TGates71 manual backup is not the priority and fear it gets back security holes over d/l. Will see.

currently we may fix manual backup so i can run manually BUT no d/l for next release. Use FTP instead to grave the files.

**Comment by TGates71** [comment]
Right. manual backup can be left disabled. Was just stating that the auto back up nightly works just fine now and the fixes were merged 4 months ago.

**Comment by e-elysiumlive88** [comment]
SENTORA IS A PIG and it's hogging up all of my resources for no reason at all

**Comment by e-elysiumlive88** [comment]
PERHAPS... Zdaemon is for zcash mining!

**Comment by rekuen** [comment]
@e-elysiumlive88 maybe your server is indeed mining cryptocurrencies but not because of sentora but because you have a website that's been compromised. Look at the services that are running and wich one is using CPU, check for Coinhive instances or suspicious scripts.

I've seen plenty of servers compromised this past month and it doesn't have anything to do with sentora. I'm running it and my CPU is perfectly fine.

**Comment by Caffe1neAdd1ct** [comment]
Make sure only one instance of the zdaemon is running at one time, do a
manual run and see if it takes too long. The runs might be stacking up or
overlapping.

Other reasons are the backup implementation in zdaemon isn't ideal. I would
recommend disabling site backups and possibly webalizer as well as these
are known performance hogs.

If you want site backups make a custom rsync / tar command.
