### ISSUE TITLE
[Feat Req] Add Default Records to Missing Domains every cron run

### ISSUE THREAD

**Issue by AldemaroC** [sentora/sentora-core#247]
Sentora should have an option to auto add default records to domains that are missing every time cron is run, just like cPanel and lots of other panels. It would be really useful to people that use Sentora WHMCS module, as this way the new domain will work out of the box.

The AddMissing() function is already done in https://github.com/sentora/sentora-core/blob/master/modules/dns_admin/code/controller.ext.php and just need to be implemented in cron.php.

It would be good also to make an option in DNS Config Module Admin to switch it on and off, as not everyone use Sentora as DNS server.

If someone have any ideia on how do to that just tell me and and I'll try to do.

**Comment by MBlagui** [comment]
Did you check roadmap ? 
http://forums.sentora.org/showthread.php?tid=2609
For feature Req/discussion you should use the forum.

Thanks closing this.
