### ISSUE TITLE
in tow moth sentora get log file bigger than 10 Gbits

### ISSUE THREAD

**Issue by calatador** [sentora/sentora-core#255]
Operating System: ubuntu 12 & ubuntu 14

Issue: too bigs log files by the time

Suggested fix or solution if you have any: compress log weekly or monthly

**Comment by MBlagui** [comment]
use log rotate. Should be added in setup next release.

**Comment by xabixab** [comment]
do you use crons?
sometimes it logs every time that it executes a cron.

**Comment by Dukecitysolutions** [comment]
We have installed/added/adjusted logrotate configs for Sentora v2 (Apache user logs, Devcote, and Proftpd).
