### ISSUE TITLE
Group Emails By Domain

### ISSUE THREAD

**Issue by amaisonneuve** [sentora/sentora-core#256]
We should alter the mailbox page to be a collapsible tree structure and group by domain, because once you get to a lot of domains and email address it get a little messy.

**Comment by TGates71** [comment]
Currently this is the default for postfix. It may be something we will look into in the future. @MBlagui

**Comment by MBlagui** [comment]
May be we can look for a solution to filter this later.

**Comment by amaisonneuve** [comment]
why is this item closed? this should be on the feature list and i can help
on this one.

can we reopen and simply retag?

**Comment by TGates71** [comment]
It's 'closed' as it was placed into the 'Backlog' section for further/future investigation ;)
https://github.com/sentora/sentora-core/milestones/Backlog
