### ISSUE TITLE
Web and Database on two servers

### ISSUE THREAD

**Issue by amaisonneuve** [sentora/sentora-core#257]
Write up a document on the process and procedures that must be taken to move the database to a separate physical server.

Lots of files to update.

**Comment by MBlagui** [comment]
Do you expect us to do it or you want to do it?

It's not supported currently. It's complicated in current setup.

**Comment by amaisonneuve** [comment]
I have done it and can document, i have this setup working right now.

**Comment by TGates71** [comment]
Post it as a guide in our forums: http://forums.sentora.org/forumdisplay.php?fid=33

**Comment by MBlagui** [comment]
I'm sure we can do that. BUT I'm more thinking about a multi server solution instead of only setting the DB on another server. It can be an issue like I had a customer hammering DB and using over 200MB/s... He would used all the external nic BW. Any guide to explain it is welcome too.
