### ISSUE TITLE
sentora is verry week in stress test

### ISSUE THREAD

**Issue by calatador** [sentora/sentora-core#261]
hi,

there are many bug in apache2 so it get down in small stress test.
it open etch request directly in apache and mysql thet mean it will eat all ram and in 20seconde mysql will down.

**Comment by MBlagui** [comment]
1. Use the forum, if you are asking for support:

http://forums.sentora.org/

2. What OS are you using? More information over the bugs you are reporting here.

If your server don't have much CPU RAM, don't expect it to handle 1000 current users per second!

If you want to help MySQL use requests caching here like W3cache or SuperCache on Wordpress.

For me not an issue.

M B

**Comment by Rakhmanov** [comment]
Since its not a bug, Close?

**Comment by 5050** [comment]
yes !
