### ISSUE TITLE
Email Logs in /var/log/sys

### ISSUE THREAD

**Issue by PhilipMcGaw** [sentora/sentora-core#263]
Can we stop email logs ending up in the syslog, they are duplicated in the mail log which is a much better place for them (Ubuntu and Sentora)

**Comment by MBlagui** [comment]
This is default system behaviour. Could explain more? kind of messages?

**Comment by CasteyDaSilva** [comment]
In /etc/rsyslog.d/50-default.conf change line:
`*.*;auth,authpriv.none              -/var/log/syslog`
to
`*.*;auth,authpriv.none,mail.!=info              -/var/log/syslog`
and restart rsyslog.

**Comment by PhilipMcGaw** [comment]
Will do that :D if it works as it looks like it should it will make sys log more pleasant to read.

**Comment by CasteyDaSilva** [comment]
It works, I've done it on my server.

**Comment by TGates71** [comment]
Bump for verification

**Comment by TGates71** [comment]
Will review this in the future. Closing for now since it is server default.
