### ISSUE TITLE
Daemon should check if a backup is already running

### ISSUE THREAD

**Issue by NitroxydeX** [sentora/sentora-core#267]
Well. The backup module seems really broken. It starts multiple backups of the same day and user. There should be a check if there is already a backup running. Is there any chance at the moment to fix this issue?

**Comment by PhilipMcGaw** [comment]
The back up module has never worked as far as I am aware. 

The advice under zpanel was to ignore it.

**Comment by MBlagui** [comment]
I disabled it and use a custom script.

**Comment by NitroxydeX** [comment]
@MBlagui could you provide your custom script for it?

**Comment by MBlagui** [comment]
https://github.com/MBlagui/Sentora-tools/blob/master/backupuserfiles.sh

That's there already

**Comment by TGates71** [comment]
I already fixed the backup module.
How-To forum post:
http://forums.sentora.org/showthread.php?tid=2065
Related updated files:
https://github.com/sentora/sentora-core/blob/9d55dc1ca2713f04851867d9522bd6ff36d88511/bin/daemon.php
https://github.com/sentora/sentora-core/blob/master/modules/backup_admin/hooks/OnDaemonDay.hook.php
Changes made:
https://github.com/sentora/sentora-core/commit/9d55dc1ca2713f04851867d9522bd6ff36d88511
https://github.com/sentora/sentora-core/commit/93ef98115da2393c9c7c2aa7d4a19cdec1d5f9e8
