### ISSUE TITLE
Sentora compatible Ubuntu 16.04.1 LTS/PHP7?

### ISSUE THREAD

**Issue by spencerthayer** [sentora/sentora-core#272]
Now that suhosin for PHP 7 is available (https://github.com/sektioneins/suhosin7) do you plan on changing the security model and sandboxing to make this compatible with Ubuntu 16.04.1 LTS/PHP7?

**Comment by MBlagui** [comment]
We will check it then. But better you use the forums for such informations

**Comment by demlasjr** [comment]
@MBlagui Not a fan of sentora and I never used it, but browsing the internet I found the forum thread saying there is no compatiblity for php7 due to suhosin.

My big question: Why this depends on suhosin when there is a better way called disable_funcions inside php.ini.

Just asking...too lazy to create a forum account just to ask this...

Cheers and great job with the panel so far.

**Comment by spencerthayer** [comment]
Yeah, @demlasjr, I haven't thought about Sentora since @MBlagui commented last. [Since then it has become clear that their team has no interest in upgrading to PHP7](http://forums.sentora.org/showthread.php?tid=3705). PHP7 had been in the works for years prior to its release and readily adopted by everyone (because it's so much better) since it's release so `IMHO` the Sentora team are working on largely irrelevant software.

**Comment by demlasjr** [comment]
Hey @spencerthayer, I agree with you here. Why don't you try vestacp meanwhile?

**Comment by TGates71** [comment]
I forgot the reason why we didn't use that when creating ZPanel. I'll look into it.
If it works properly, then we should be able to change that line to:
`disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,passthru,show_source,shell_exec,system,popen,pclose,proc_open,proc_nice,proc_terminate,proc_get_status,proc_close,leak,apache_child_terminate,posix_kill,posix_mkfifo,posix_setpgid,posix_setsid,posix_setuid,escapeshellcmd,escapeshellarg,exec`

**Comment by demlasjr** [comment]
That sounds great @TGates71. I used suhosin before but I switched to disable_functions and had no security issues. I use fastcgi and chroot too. I even blocked php mail with that line forcing customers using smtp instead

**Comment by TGates71** [comment]
Ok, so here's the deal. disable_functions only works in the php.ini and is not available on a per vhost directive. So, for this security model, suhosin is still required even with the new php 7.
For some reason they have not added the ability to control it per vhost even though a large amount of the community would like to be able to use it that way. Go figure..

**Comment by allebb** [comment]
I guess Sentora could use the use Apache's PHPINIDir directive and then write and reference a user specific php.ini file (for specific function disablements and openbasddir etc) at account creation time?

That would be an option I guess :)

**Comment by demlasjr** [comment]
Php.ini can be rewrited by .user.ini inside the user account, if each
account have different apache processes user/owner (don't know how Sentora
is set since I never used it, I only used Zabel when it was released). If
you don't want to give user access to edit that file, it can be set with
root only permissions, for example.

**Comment by MBlagui** [comment]
No it won't work we need to use SuPHP so php runs in user context and it's a different setup from current. it would allow also to run Python and CGI. Require more work in apache stack.
