### ISSUE TITLE
Update PHPMyAdmin to latest 4.6.4

### ISSUE THREAD

**Issue by amaisonneuve** [sentora/sentora-core#275]
Need to upgrade these components as they are dated..

Upgrade PHPMyAdmin to latest 4.6.4

**Comment by TGates71** [comment]
There are some issues with this.
Some OS distributions have a lower minimal PHP/MySQL version that the current phpmyadmin will not run on. For those using PHP 5.5.0 or newer AND MySQL 5.5 or newer/MariaDB 5.5 or newer may use the 'phpmyadmin-au' module which will auto-update it to latest version.

For users on older distributions, they will need to remain on an older version.

**Comment by amaisonneuve** [comment]
Agreed, but as a go forward strategy we should increase the minimum requirements for future versions to 5.5 for both PHP and MySQL/MariaDB. No?

**Comment by TGates71** [comment]
Correct. This is already planned as we update the code and installers for newer OS versions.

**Comment by MBlagui** [comment]
We should instead install different phpmyadmin depending on OS/ PHP installed.
I can be done.

**Comment by TGates71** [comment]
Updated in v2
