### ISSUE TITLE
Prevent being blamed for spam

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-core#276]
Make 'auto-branding' by showing a 'Hosted by' URL above the 'Powered by' URL using the hosted domain's URL.

**Comment by TGates71** [comment]
Also need to change all of the static pages to be more generic (or use the domain's url) instead of a big 'Sentora' on the top. Just use a 'powered by' at the bottom.

**Comment by MBlagui** [comment]
I think that cpanel & parallels have the same branding. 

We might instead add email abuse@hosting for such reports no?

**Comment by TGates71** [comment]
Adding an abuse email would be good, but who knows if these spammers even set up an abuse account.

**Comment by 5050** [comment]
Most of the time, the master email is not set and leaved to zadmin@localhost which will not help. 
The best would be to be able to grab at setup the abuse of the server host or domain host, but i do not see how to do it !

**Comment by TGates71** [comment]
I don't see a way either...

**Comment by MBlagui** [comment]
We can do that. We can either reverse the server hostname or use the cpanel domain for that.

M B

**Comment by TGates71** [comment]
I have no new ideas or updates for it.

**Comment by TGates71** [comment]
Bump verification needed if addressed in v2
