### ISSUE TITLE
Sub Domains not displaying/creating properly

### ISSUE THREAD

**Issue by NigelNapier** [sentora/sentora-core#278]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System: Ubuntu 

Operating System Version number: 14.04 LTS

Sentora Version: 1.0.4

Issue: I installed the latest development snapshot for testing & as I was creating sub-domains it wouldn't display them properly. The bottom sub-domain in my picture was created using files from Sentora version 1.0.3
![dns-manager](https://cloud.githubusercontent.com/assets/1205726/20247478/2d86e5ec-aa32-11e6-9b5a-ffdecb4bb7d6.png)

How to reproduce it: As above.

Suggested fix or solution if you have any:

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by MBlagui** [comment]
We will investigate this before any release.

Thanks for the report.

**Comment by Dukecitysolutions** [comment]
Don't see any issues with this in V2. Closing for now.
