### ISSUE TITLE
Name Server Manager

### ISSUE THREAD

**Issue by PS2Guy** [sentora/sentora-core#279]
Add a Name Server Manager to the core for better setting of network.

**Comment by MBlagui** [comment]
Could you explain more your request? You want to manager ns1/ns2 settings? Able to have slave servers on remote servers?

**Comment by PS2Guy** [comment]
I would like to be able to have a manager where you can setup name servers that then display in the domain manager.
Currently the only way to setup and add ns3 e.t.c is to do it manually in the database.

**Comment by MBlagui** [comment]
Could you elaborate more please as I don't get it? I'm not using too much the NS feature but it seems working fine for me. 

Do you want to setup default records?

**Comment by TGates71** [comment]
I just use the NS tab under DNS manager to add more name server records.

**Comment by PS2Guy** [comment]
With a name server manager you wouldn't need to change all 100 (for example) of your domains that way.
When you add a new domain the name server would automatically be set.

**Comment by MBlagui** [comment]
Mainly you would set a global DNS entry for the whole account. That's not a name server manager.

I know the feature as I have used it on another panel before. Need planning & time.
