### ISSUE TITLE
Will Sentora ever see the light again?

### ISSUE THREAD

**Issue by vikhyatgeek** [sentora/sentora-core#284]
It's been such....... a long time since the release of Sentora 1.0.3 and no updates till now. Sentora doesn't even officially support php 5.6 and is still with php 5.5 whose support has also ended. Just see other control panels like VestaCP.  Seriously guys, is Sentora ever gonna see the light again or someone or maybe me needs to create a new edition of Sentora and provide a script to everyone to upgrade to my version and take all of your users?

**Comment by MBlagui** [comment]
yep don't worry. Also if you would like to discuss about this please use the forum.
