### ISSUE TITLE
New Dev

### ISSUE THREAD

**Issue by amaisonneuve** [sentora/sentora-core#286]
Ok, now seriously we need to get some new dev going.. this is crazy.

What needs to happen?

Who can accept PR's?

I have 50 sites running and i need to get stuff more organized.

Now if nobody wants to contribute, that is fine lets just get a process to ensure that PR's are accepted.

**Comment by MBlagui** [comment]
We are preparing a release and not refusing PR.

We will implement git flow and setup some guidelines over PR and we want to implement a full QA process too. That's a lot of work to ensure that any modification won't impact any other feature and trigger a regression.

And as always all help is welcome.
