### ISSUE TITLE
Sentora 1.0.4 Feb release

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-core#288]
Planning for a maintenance release before we set a more regular release cycle

Many fixes and few enhancements.

We should ensure that the patches in master don't introduce regression.

We need to build a patch for 1.0.4 // Updater.

http://forums.sentora.org/showthread.php?tid=3550

**Comment by amaisonneuve** [comment]
So how are things? i haven't seen any commits that are related to the new 1.0.4 build, how can i help?

**Comment by MBlagui** [comment]
We are testing currently and frozen the branch.

**Comment by chongma** [comment]
i was thinking about how to test as the linux machines i have access are all production servers.  i develop on osx as well so that is no good.  maybe i could run a virtualbox server inside osx and get it running on there?

**Comment by MBlagui** [comment]
Yep I use vmware / Virtualbox but we have a lot of work to improve testing routines. It's my daily job but priority is validating the release then I will get some time to setup a clean CI server/testing for sentora.

**Comment by amaisonneuve** [comment]
What's the name of the testing branch?

**Comment by MBlagui** [comment]
The master currently after this release we will move to gitflow and clean up that too.

**Comment by amaisonneuve** [comment]
But i don't see any commits, the last commit to master was 3 months ago. i'm sure there is alot more work that was done.

**Comment by amaisonneuve** [comment]
where a the commits for this new version?

**Comment by TGates71** [comment]
Working on it my friend. I accepted some pull requests today that I was able to test and verify.

**Comment by chongma** [comment]
i have installed a virtualbox with centos 7.  i just need to enable the network.  what is the best way to install the current testing version?

**Comment by Ron-e** [comment]
Is 1.0.4 FEB beta/rc still a private branch or tag?
I can not see any 1.0.4 branch or tag.

**Comment by amaisonneuve** [comment]
Any progress on this?

**Comment by MBlagui** [comment]
We are still heavily working on it sir. Sorry for the delay but I've been my self too busy last 2 weeks.

**Comment by amaisonneuve** [comment]
I'm would really appreciate an update.. more than working on it.. i understand we are all under the gun on multiple fronts. Its just i'm trying to run a business here and would like a status on whats fixed whats outstanding and what i can help with.. the communication from the main team is really lacking right now.. i want to help.. and help us all.. i have key issues that need sorting out and they are not working.. i can work and be done with it but i want to work with you all and get this back as the community it was and could be .

**Comment by amaisonneuve** [comment]
crickets!!!.. where is the code base being managed out of i don't see any 1.0.4 branch?

I'd really like to see whats coming in this release.

**Comment by MBlagui** [comment]
This is a maintenance release that would setup a faster release cycle. Sorry been too busy on this and it's obvious we need to setup a roadmap so all users get more infos how it's going on.

First fixes and more features in next release.

**Comment by amaisonneuve** [comment]
Awesome agree 100%

In terms of the branch tag or whatever it would be nice and fast to setup and see. Right now I see the last commit of any usefulness being months and yrs ago.

It's brutal being on the outside.. I'm running a business on this and want to commit or help or add but I have no idea what you guys are doing or who has what where..

Can we take an hour of you day to get that setup?

**Comment by chongma** [comment]
i agree with @amaisonneuve that if the development were open source and visible to everyone on github then we could submit suggestions and PRs.  it is not obvious where the development is actually taking place.  it would also help to be able to see progress.

**Comment by MBlagui** [comment]
most of the code is already open guys. As I said this is a fix release.

I had not pushed only few last minute fixes that's all missing in current master. But we will change how the project is built and add CI/ Tests.

**Comment by amaisonneuve** [comment]
Ok then there are no changes of any significant benefit and the last change was over 1 yr old. This is very concerning.

Is anyone looking at the backup process? Why is this process not dumping the core sentora tables? 

How domains are managed, when you have more than one domain the long lists get out of hand.

All of the underlying tools are very dated.

And we need to seriously upgrade the minimum php version.

There is a long list of pull requests, lets clean that up .

Why focus on code reorganization that is taking so long and preventing any advancement.

**Comment by amaisonneuve** [comment]
I know we are all busy, but can someone please provide some insight as to status and also create the 1.0.4 branch? as of right now i see nothing and have some serious concerns.. 

Can someone respond to my previous note? 

There is a community of users here that are completely in the dark, and better yet a community of developers willing to pitch in some much needed features.

Forget code reorganization and lets get some features.. some upgraded tools and some communication.

If you guys aren't into this please add me as an admin and i will move this thing forward and build out communication with the community of users.

**Comment by TGates71** [comment]
@MBlagui 
Is it possible to start a 1.0.4 branch at least with all the current fixes? What is the plan?

About the backup process, it wasn't designed for the core, just for user accounts. Most users use 3rd-party programs to do this for them.

**Comment by MBlagui** [comment]
yep I will push it as it's overdue

**Comment by amaisonneuve** [comment]
so how are we doing? i still don't see anything?

**Comment by ettienneb** [comment]
Think this project is now dead as a doorknob..... Updates have been promised since who knows when, pity as this looked promising... anyway, plenty of alternatives out there, ISPconfig for one is not to bad

**Comment by chongma** [comment]
Thanks for the hint. I will check out ISPConfig. Project looks active

**Comment by MBlagui** [comment]
Notice this the base for 1.0.4 we will release fixes mainly but try to reboot the build process so we can do releases faster:
https://github.com/sentora/sentora-core/tree/1.0.4

**Comment by Dlair** [comment]
I am very unhappy at the lack of communication and openness around here. You have contributors begging to help you and they're being ignored. This is not the principles of open source and transparency.

**Comment by amaisonneuve** [comment]
Amen

**Comment by ettienneb** [comment]
They should either can this project or hand it over to devs that want to contribute....  Sentora is getting such a bad name for lack of commitment, that it will be hard to resurrect it again... 
Suppose thats what happened to Zpanel...
Zpanel --> Sentora --> Kill switch.

Ive moved over to ISPconfig, not a bad CP, also open source, and there seems to be a hell of a lot more activity going on there...
