### ISSUE TITLE
Gravatar image cause Mixed-Content

### ISSUE THREAD

**Issue by xabixab** [sentora/sentora-core#289]
Gravatar image is loaded through http causing mixed-content.

![sentora-mixed-content](https://cloud.githubusercontent.com/assets/9028870/23095429/1e5570ba-f60a-11e6-94f0-904994b9fd97.png)

 -----------------

For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System: Ubuntu 

Operating System Version number: 14.04

Sentora Version: 1.0.3

Issue: Mixed content in panel.

How to reproduce it: Use HTTPS in sentora panel.

Suggested fix or solution if you have any: Self-host image or use HTTPS instead. (The image is available through HTTPS in gravatar web page)

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by MrKaKisen** [comment]
This is solved now.

See here: https://github.com/sentora/sentora-core/pull/299
