### ISSUE TITLE
email are sent with panel address head

### ISSUE THREAD

**Issue by calatador** [sentora/sentora-core#290]
email are sent using panel address , and this cause ptr problem .
so this my be a bug with roundcube integration
and can be future with phpsend mail to detect domain where is it sent from

**Comment by chongma** [comment]
is this a copy of #258?

**Comment by TGates71** [comment]
@Dukecitysolutions I haven't noticed any issues with this with SPF and DMARC entries.

**Comment by TGates71** [comment]
Already reported #258
