### ISSUE TITLE
ADD: Create default DNS message

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-core#292]
Add a message to the Domain Manager that will notify the user to use the DNS Manager to create the default DNS entries if using Sentora's DNS.

Also add a similar message to the Sub Domain Manager to notify the user to add a matching CNAME record if using Sentora's DNS.

**Comment by TGates71** [comment]
Or, have the domain manager auto-create the default entries? I believe we discussed something about this @Dukecitysolutions

**Comment by Dukecitysolutions** [comment]
Yes, depends how you setup your domain provider’s DNS. Some hosters use providers dns and others forward dns to Sentora servers. Users should already know how to use dns. Sentora has docs to explain this. We are not responsible if users don’t read documentation before setup and choose to setup without knowing how to use it. Closing.
