### ISSUE TITLE
[Web Interface] - Password input is showed after adding FTP Account

### ISSUE THREAD

**Issue by cepix** [sentora/sentora-core#295]
Operating System: Ubuntu 14.04.5 LTS

Operating System Version number:
(GNU/Linux 3.13.0-107-generic x86_64)

Sentora Version: Stable (installed by bash <(curl -L -Ss http://sentora.org/install) )

Issue: 
Password input is showed after adding FTP Account

How to reproduce it:
Log to web interface
File
FTP Account.
Enter **something** and **some_password**

**Only possible name is zadmin_**something**.
**some_password** is showed in the list

Suggested fix or solution if you have any:
If sub-domain is null, set apache config to use ServerName value to localhost

Comment:
![image](https://cloud.githubusercontent.com/assets/12740590/24489054/725f62dc-14f1-11e7-9d78-7f9994d0e71a.png)

**Comment by TGates71** [comment]
According to your screenshot, 'show passwords' is enabled.
