### ISSUE TITLE
Email Server Configuration

### ISSUE THREAD

**Issue by edofritz** [sentora/sentora-core#296]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System: Ubuntu

Operating System Version number: 14.04.5 LTS

Sentora Version:

Issue: Delay Mail's from GMAIL

How to reproduce it:
Some one hace a complete email server configuration? thanks

Suggested fix or solution if you have any:

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.
