### ISSUE TITLE
Package manager bug

### ISSUE THREAD

**Issue by PS2Guy** [sentora/sentora-core#300]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System: Ubuntu

Operating System Version number: 14.04

Sentora Version: 1.0.x

Issue: Create a package doesn't work in any version of sentora.
All packages have to be created manually in the database.

**Comment by TGates71** [comment]
Works fine on my production U14 and C6.8 Test VM.

**Comment by MBlagui** [comment]
Desktop Ubuntu? Or server? Could you check server logs?

**Comment by PS2Guy** [comment]
Sentora doesn't actually install in Ubuntu Desktop @MBlagui 

It's not working on any of my test & production machines.

**Comment by TGates71** [comment]
Correct @PS2Guy Sentora does not run/install properly with desktop versions. There is a conflict. I can't remember what exactly (Was a long time ago I came across this).

**Comment by PS2Guy** [comment]
@TGates71, when I try it uninstalls the desktop for some reason.

I'll fire up a machine & try to replicate this bug again & grab a screen shot.

**Comment by TGates71** [comment]
See issue mentioned above.

**Comment by rizwan95** [comment]
Same issue here. I am running on Centos 6.5 , it doesn't seem to work.

**Comment by MBlagui** [comment]
@rizwan95 do you mean centos 6.5 server or desktop edition. We never test it on desktop editions we always test it on minimal server editions.

**Comment by rizwan95** [comment]
@MBlagui : I meant Centos 6.5 server edition
