### ISSUE TITLE
Problem After Update PHP 5.4

### ISSUE THREAD

**Issue by kridaweb** [sentora/sentora-core#302]
Some time ago, I was updating sentora to PHP 5.6 because my program requires at least php version 5.4 and above and requires IonCube. I've managed to add IonCube and upgrade to PHP version 5.6, but there is a problem that occurs when I try to make the username for the database is always error 500 or internal server error. How to fix it? Or is there a way to restore the php version to the built-in version of the sentora?

**Comment by amaisonneuve** [comment]
post your php_error.log or atleast where the error is.

**Comment by MBlagui** [comment]
Can you post on forum please? Seem you messed up your php install. So please provide more infos on the forum: http://forums.sentora.org/
