### ISSUE TITLE
Register sub-domain as domain based on someone else's domain

### ISSUE THREAD

**Issue by mrgreen6466** [sentora/sentora-core#309]
Hello, i found little bug:

When i create single user in sentora and grant in package 1 domain only, he can register it as sub-domain in domain module even he doesnt have any domains! Let me explain:
user1: has his own domain bruto.sk
user2: doesnt have any domain, but can register anything.bruto.sk

I mean he can register sub-domains based on someone else´s domain. 
This problem is only in domain module

If user want to register subdomain via normal way (aka. sub-domain module) there is list box of his domains and he cant register any sub-domains if he doesnt have any equivalent domains. This way is OK!!!
------------------------------------------------------------------------------------------------------------

My opinion for fix:
1. User cant register anything.bruto.sk if he doesnt have any equivalent registered domains
2. When user has registered domains, he cant register anything.bruto.sk in DOMAIN MODULE
*domain module is for domains!!! not for sub-domains, if you know what i mean.

**Comment by mrgreen6466** [comment]
![bez nazvu](https://user-images.githubusercontent.com/30244172/28881358-2b55ce70-77a8-11e7-9402-1c953f872854.png)
![bez nazvu](https://user-images.githubusercontent.com/30244172/28881436-655b0c02-77a8-11e7-89a1-466e8d106e2e.png)

**Comment by 5050** [comment]
This is more complex, or simple, depending how you see it :

1) If a user create a subdomain on his server without setup a DNS record to point to it, the subdomain hosted is completely useless. (except for people who setup the subdomain in their host file : very limited !).

2) A real case that I'm currently using for 2 subdomains :
- A friend owns the main domain "domain.tld". He hosts a website for it on his server and manage his DNS records.
- We want to host a new website "service.domain.tld" on my server,

-> My friend adds a "A" DNS entry to his zone for "service" subdomain of "domain.tld", pointing to my server.
-> I have to create on my server only the pseudo-subdomain "service.friend.com". 
The only reliable solution is to create it as "main domain"

Do you maintain your request ?  ;-)

**Comment by TGates71** [comment]
Also this is by design for when you use the 'shared domains' feature. The server admin can add domains he owns in Module Admin > Apache Config > Shared Domains. This allows clients to add sub domains using his domain if he chooses, but it also allows the use of sites like no-ip.com and dyndns.com for clients who do not use or buy a domain.

**Comment by mrgreen6466** [comment]
5050: yes but friend n.1 have dns record look like everything.friend1.tld is pointing to my server
and friend n.2 can register via unauthorized way subdomain.friend1.tld and this kind of unauthorized subdomain is fully functional :(

My actual fix is: customer open tiket for register domain and i must manually register it to prevent this.

**Comment by modcar** [comment]
But, if you’re saying “you can have one domain” whats the difference between them having “domain.com” OR “anything.domain.com”? They still have 1 domain only

**Comment by mrgreen6466** [comment]
You missunderstand, problem is not limit of max domains, problem is when user1 has his own domain (user1domain.tld) but somebody else (user2) can register something.user1domain.tld. 
Know you what i mean?

**Comment by TGates71** [comment]
Ok, I will take a look at it when I get home tonight.

**Comment by TGates71** [comment]
When I try to reproduce it as you have described, Sentora preforms as intended.
When trying to use a domain from another clients account I receive the error:

> You cannot add a Sub-Domain here. Please use the Subdomain manager to add Sub-Domains.

Also, when I use on of my shared domains it adds the sub domain as expected.

**Comment by TGates71** [comment]
After further testing I can not reproduce this behavior. I tried with several different accounts and domains.
I will compare the controller.ext.php on GitHub with my version and see if there are any differences.

**Comment by TGates71** [comment]
After a comparison with my versiob and this version on GitHub: https://github.com/sentora/sentora-core/blob/1.0.4/modules/domains/code/controller.ext.php I find there are no differences.

**Comment by mrgreen6466** [comment]
Ou, im using debian version (1.0.3) and running on debian 8. 
When I try to reproduce it as i´ve described, sentora can fully register any subdomain even the user dont have registered domains. And there is not any error message as you described.
After register there is only:
> Changes to your domain web hosting has been saved successfully.

I tried to manualy copy content from (git) domain controller.ext.php to /etc/sentora/panel/modules/domains/code/controller.ext.php and i dont see any differences :(


I think all my domains in sentora are behave: registered as shared domains
My shared domains look-like: 

> no-ip,dyndns,autono,zphub

**Comment by TGates71** [comment]
I do not have access to a debian box to test if it is OS specific. Anybody else using debian 8 and getting a similar behavior?
