### ISSUE TITLE
Update the PHP version to 5.6

### ISSUE THREAD

**Issue by rizwan95** [sentora/sentora-core#310]
The PHP version which comes preinstalled with sentora is v5.3. Please upgrade it to v5.6.

**Comment by Ron-e** [comment]
Sentora isn't shipped with php, it uses the OS default php. check out the forum for more info about upgrading:  http://forums.sentora.org/index.php

**Comment by rizwan95** [comment]
I have updated php to 5.6 by myself following the steps provided in the sentora forum. Thanks !
