### ISSUE TITLE
found missing or error in the installation 

### ISSUE THREAD

**Issue by clouzone** [sentora/sentora-core#311]
Hi, 

If found some of the codes are missing while installing, I followed the installation on the page [Link](http://docs.sentora.org/?node=22) Below are the error lines. Please check the installation log.. In our another server when we installed the sentora we are able to create email address in the name of our sub domain name we used/pointed to login sentora. But in this installation we are not able to see the sub domain in drop down of creating an email account

`-- Updating repositories and packages sources
--2017-10-21 15:26:20--  http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-re                  lease-7-10.noarch.rpm
Resolving dl.fedoraproject.org (dl.fedoraproject.org)... 209.132.181.23, 209.132                  .181.25, 209.132.181.24
Connecting to dl.fedoraproject.org (dl.fedoraproject.org)|209.132.181.23|:80...                   connected.
HTTP request sent, awaiting response... 200 OK
Length: 14848 (14K) [application/x-rpm]
Saving to: 'epel-release-7-10.noarch.rpm'

     0K .......... ....                                       100%  106K=0.1s

2017-10-21 15:26:20 (106 KB/s) - 'epel-release-7-10.noarch.rpm' saved [14848/148                  48]

sed: can't read /etc/selinux/config: No such file or directory
install: line 370: setenforce: command not found
Redirecting to /bin/systemctl stop sendmail.service
Failed to stop sendmail.service: Unit sendmail.service not loaded.
error reading information on service sendmail: No such file or directory
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.
Redirecting to /bin/systemctl stop firewalld.service
Failed to stop firewalld.service: Unit firewalld.service not loaded.
error reading information on service firewalld: No such file or directory

-- Listing of all packages installed:
GeoIP-1.5.0-11.el7.x86_64
acl-2.2.51-12.el7.x86_64
audit-libs-2.7.6-3.el7.x86_64
basesystem-10.0-7.el7.centos.noarch
bash-4.2.46-29.el7_4.x86_64
bind-libs-9.9.4-51.el7.x86_64
bind-license-9.9.4-51.el7.noarch
bind-utils-9.9.4-51.el7.x86_64
binutils-2.25.1-32.base.el7_4.1.x86_64
bzip2-libs-1.0.6-13.el7.x86_64
ca-certificates-2017.2.14-71.el7.noarch
centos-release-7-4.1708.el7.centos.x86_64
chkconfig-1.7.4-1.el7.x86_64
coreutils-8.22-18.el7.x86_64
cpio-2.11-25.el7_4.x86_64
cracklib-2.9.0-11.el7.x86_64
cracklib-dicts-2.9.0-11.el7.x86_64
cryptsetup-libs-1.7.4-3.el7.x86_64
curl-7.29.0-42.el7.x86_64
cyrus-sasl-lib-2.1.26-21.el7.x86_64
dbus-1.6.12-17.el7.x86_64
dbus-libs-1.6.12-17.el7.x86_64
device-mapper-1.02.140-8.el7.x86_64
device-mapper-libs-1.02.140-8.el7.x86_64
diffutils-3.3-4.el7.x86_64
dracut-033-502.el7.x86_64
e2fsprogs-libs-1.42.9-10.el7.x86_64
ed-1.9-4.el7.x86_64
elfutils-default-yama-scope-0.168-8.el7.noarch
elfutils-libelf-0.168-8.el7.x86_64
elfutils-libs-0.168-8.el7.x86_64
epel-release-7-10.noarch
expat-2.1.0-10.el7_3.x86_64
file-libs-5.11-33.el7.x86_64
filesystem-3.2-21.el7.x86_64
findutils-4.5.11-5.el7.x86_64
fipscheck-1.4.1-6.el7.x86_64
fipscheck-lib-1.4.1-6.el7.x86_64
gawk-4.0.2-4.el7_3.1.x86_64
gdbm-1.10-8.el7.x86_64
glib2-2.50.3-3.el7.x86_64
glibc-2.17-196.el7.x86_64
glibc-common-2.17-196.el7.x86_64
gmp-6.0.0-15.el7.x86_64
gnupg2-2.0.22-4.el7.x86_64
gpg-pubkey-f4a80eb5-53a7ff4b
gpgme-1.3.2-5.el7.x86_64
grep-2.20-3.el7.x86_64
groff-base-1.22.2-8.el7.x86_64
gzip-1.5-9.el7.x86_64
hardlink-1.0-19.el7.x86_64
hostname-3.13-3.el7.x86_64
info-5.1-4.el7.x86_64
initscripts-9.49.39-1.el7.x86_64
iproute-3.10.0-87.el7.x86_64
iptables-1.4.21-18.2.el7_4.x86_64
iputils-20160308-10.el7.x86_64
keyutils-libs-1.5.8-3.el7.x86_64
kmod-20-15.el7_4.4.x86_64
kmod-libs-20-15.el7_4.4.x86_64
kpartx-0.4.9-111.el7.x86_64
krb5-libs-1.15.1-8.el7.x86_64
less-458-9.el7.x86_64
libacl-2.2.51-12.el7.x86_64
libassuan-2.1.0-3.el7.x86_64
libattr-2.4.46-12.el7.x86_64
libblkid-2.23.2-43.el7.x86_64
libcap-2.22-9.el7.x86_64
libcap-ng-0.7.5-4.el7.x86_64
libcom_err-1.42.9-10.el7.x86_64
libcurl-7.29.0-42.el7.x86_64
libdb-5.3.21-20.el7.x86_64
libdb-utils-5.3.21-20.el7.x86_64
libedit-3.0-12.20121213cvs.el7.x86_64
libffi-3.0.13-18.el7.x86_64
libgcc-4.8.5-16.el7.x86_64
libgcrypt-1.5.3-14.el7.x86_64
libgpg-error-1.12-3.el7.x86_64
libidn-1.28-4.el7.x86_64
libmnl-1.0.3-7.el7.x86_64
libmount-2.23.2-43.el7.x86_64
libnetfilter_conntrack-1.0.6-1.el7_3.x86_64
libnfnetlink-1.0.1-4.el7.x86_64
libpwquality-1.2.3-4.el7.x86_64
libselinux-2.5-11.el7.x86_64
libsemanage-2.5-8.el7.x86_64
libsepol-2.5-6.el7.x86_64
libssh2-1.4.3-10.el7_2.1.x86_64
libstdc++-4.8.5-16.el7.x86_64
libtasn1-4.10-1.el7.x86_64
libtirpc-0.2.4-0.10.el7.x86_64
libuser-0.60-7.el7_1.x86_64
libutempter-1.1.6-4.el7.x86_64
libuuid-2.23.2-43.el7.x86_64
libverto-0.2.5-4.el7.x86_64
libxml2-2.9.1-6.el7_2.3.x86_64
lm_sensors-libs-3.4.0-4.20160601gitf9185e5.el7.x86_64
lua-5.1.4-15.el7.x86_64
mariadb-libs-5.5.56-2.el7.x86_64
ncurses-5.9-14.20130511.el7_4.x86_64
ncurses-base-5.9-14.20130511.el7_4.noarch
ncurses-libs-5.9-14.20130511.el7_4.x86_64
net-snmp-5.7.2-28.el7.x86_64
net-snmp-agent-libs-5.7.2-28.el7.x86_64
net-snmp-libs-5.7.2-28.el7.x86_64
net-snmp-utils-5.7.2-28.el7.x86_64
nspr-4.13.1-1.0.el7_3.x86_64
nss-3.28.4-15.el7_4.x86_64
nss-pem-1.0.3-4.el7.x86_64
nss-softokn-3.28.3-8.el7_4.x86_64
nss-softokn-freebl-3.28.3-8.el7_4.x86_64
nss-sysinit-3.28.4-15.el7_4.x86_64
nss-tools-3.28.4-15.el7_4.x86_64
nss-util-3.28.4-3.el7.x86_64
openldap-2.4.44-5.el7.x86_64
openssh-7.4p1-13.el7_4.x86_64
openssh-clients-7.4p1-13.el7_4.x86_64
openssh-server-7.4p1-13.el7_4.x86_64
openssl-libs-1.0.2k-8.el7.x86_64
p11-kit-0.23.5-3.el7.x86_64
p11-kit-trust-0.23.5-3.el7.x86_64
pam-1.1.8-18.el7.x86_64
passwd-0.79-4.el7.x86_64
pcre-8.32-17.el7.x86_64
perl-5.16.3-292.el7.x86_64
perl-Carp-1.26-244.el7.noarch
perl-Data-Dumper-2.145-3.el7.x86_64
perl-Encode-2.51-7.el7.x86_64
perl-Exporter-5.68-3.el7.noarch
perl-File-Path-2.09-2.el7.noarch
perl-File-Temp-0.23.01-3.el7.noarch
perl-Filter-1.49-3.el7.x86_64
perl-Getopt-Long-2.40-2.el7.noarch
perl-HTTP-Tiny-0.033-3.el7.noarch
perl-PathTools-3.40-5.el7.x86_64
perl-Pod-Escapes-1.04-292.el7.noarch
perl-Pod-Perldoc-3.20-4.el7.noarch
perl-Pod-Simple-3.28-4.el7.noarch
perl-Pod-Usage-1.63-3.el7.noarch
perl-Scalar-List-Utils-1.27-248.el7.x86_64
perl-Socket-2.010-4.el7.x86_64
perl-Storable-2.45-3.el7.x86_64
perl-Text-ParseWords-3.29-4.el7.noarch
perl-Time-HiRes-1.9725-3.el7.x86_64
perl-Time-Local-1.2300-2.el7.noarch
perl-constant-1.27-2.el7.noarch
perl-libs-5.16.3-292.el7.x86_64
perl-macros-5.16.3-292.el7.x86_64
perl-parent-0.225-244.el7.noarch
perl-podlators-2.5.1-3.el7.noarch
perl-threads-1.87-4.el7.x86_64
perl-threads-shared-1.43-6.el7.x86_64
pinentry-0.8.1-17.el7.x86_64
pkgconfig-0.27.1-4.el7.x86_64
popt-1.13-16.el7.x86_64
procps-ng-3.3.10-16.el7.x86_64
psmisc-22.20-15.el7.x86_64
pth-2.0.7-23.el7.x86_64
pygpgme-0.3-9.el7.x86_64
pyliblzma-0.5.3-11.el7.x86_64
python-2.7.5-58.el7.x86_64
python-iniparse-0.4-9.el7.noarch
python-libs-2.7.5-58.el7.x86_64
python-pycurl-7.19.0-19.el7.x86_64
python-urlgrabber-3.10-8.el7.noarch
pyxattr-0.5.1-5.el7.x86_64
qrencode-libs-3.4.1-3.el7.x86_64
quota-4.01-14.el7.x86_64
quota-nls-4.01-14.el7.noarch
readline-6.2-10.el7.x86_64
rootfiles-8.1-11.el7.noarch
rpcbind-0.2.0-42.el7.x86_64
rpm-4.11.3-25.el7.x86_64
rpm-build-libs-4.11.3-25.el7.x86_64
rpm-libs-4.11.3-25.el7.x86_64
rpm-python-4.11.3-25.el7.x86_64
sed-4.2.2-5.el7.x86_64
setup-2.8.71-7.el7.noarch
shadow-utils-4.1.5.1-24.el7.x86_64
shared-mime-info-1.8-3.el7.x86_64
sqlite-3.7.17-8.el7.x86_64
systemd-219-42.el7_4.4.x86_64
systemd-libs-219-42.el7_4.4.x86_64
systemd-sysv-219-42.el7_4.4.x86_64
sysvinit-tools-2.88-14.dsf.el7.x86_64
tar-1.26-32.el7.x86_64
tcp_wrappers-7.6-77.el7.x86_64
tcp_wrappers-libs-7.6-77.el7.x86_64
tmpwatch-2.11-5.el7.x86_64
tzdata-2017b-1.el7.noarch
ustr-1.0.4-16.el7.x86_64
util-linux-2.23.2-43.el7.x86_64
vim-minimal-7.4.160-2.el7.x86_64
vzdummy-systemd-el7-1.0-4.noarch
wget-1.14-15.el7.x86_64
xz-5.2.2-1.el7.x86_64
xz-libs-5.2.2-1.el7.x86_64
yum-3.4.3-154.el7.centos.noarch
yum-metadata-parser-1.1.4-10.el7.x86_64
yum-plugin-fastestmirror-1.1.31-42.el7.noarch
zlib-1.2.7-17.el7.x86_64

-- Updating+upgrading system, it may take some time...
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: fr.mirror.babylon.network
No packages marked for update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirrors.ircam.fr
No packages marked for update

-- Downloading and installing required tools...
Package chkconfig-1.7.4-1.el7.x86_64 already installed and latest version
warning: /var/cache/yum/x86_64/7/epel/packages/lyx-fonts-2.2.3-1.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Public key for lyx-fonts-2.2.3-1.el7.noarch.rpm is not installed
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-10.noarch (installed)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Package curl-7.29.0-42.el7.x86_64 already installed and latest version
Package libxml2-2.9.1-6.el7_2.3.x86_64 already installed and latest version
Package zip-3.0-11.el7.x86_64 already installed and latest version
Package 1:make-3.82-23.el7.x86_64 already installed and latest version

-- Downloading Sentora, Please wait, this may take several minutes, the installer will continue after this is complete!
2017-10-21 15:35:59 URL:https://codeload.github.com/sentora/sentora-core/zip/1.0.0 [21498409] -> "sentora_core.zip" [1]
--2017-10-21 15:36:00--  https://raw.githubusercontent.com/sentora/sentora-core/b176df0e29e52e14d778ca6cb47c5765cf3c4953/modules/ftp_management/code/controller.ext.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20422 (20K) [text/plain]
Saving to: 'hotfix_controller.ext.php'

     0K .......... .........                                  100% 3.56M=0.005s

2017-10-21 15:36:00 (3.56 MB/s) - 'hotfix_controller.ext.php' saved [20422/20422]

2017-10-21 15:36:02 URL:https://codeload.github.com/sentora/sentora-installers/zip/1.0.3 [85928] -> "sentora_preconfig.zip" [1]
install: line 546: chattr: command not found

-- Installing MySQL
Redirecting to /bin/systemctl start mariadb.service
Created symlink from /etc/systemd/system/multi-user.target.wants/mariadb.service to /usr/lib/systemd/system/mariadb.service.

-- Installing Postfix
ERROR 1005 (HY000) at line 98: Can't create table 'sentora_postfix.vacation_notification' (errno: 150)
Created symlink from /etc/systemd/system/multi-user.target.wants/postfix.service to /usr/lib/systemd/system/postfix.service.

-- Installing Dovecot
Created symlink from /etc/systemd/system/multi-user.target.wants/dovecot.service to /usr/lib/systemd/system/dovecot.service.

-- Installing and configuring Apache

-- Installing and configuring PHP

# Building suhosin
2017-10-21 15:47:28 URL:https://codeload.github.com/sektioneins/suhosin/zip/0.9.37.1 [238480] -> "suhosin.zip" [1]
Installing shared extensions:     /usr/lib64/php/modules/
Created symlink from /etc/systemd/system/multi-user.target.wants/httpd.service to /usr/lib/systemd/system/httpd.service.
Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.

-- Installing ProFTPD
Created symlink from /etc/systemd/system/multi-user.target.wants/proftpd.service to /usr/lib/systemd/system/proftpd.service.

-- Installing and configuring Bind
Package 32:bind-utils-9.9.4-51.el7.x86_64 already installed and latest version
Package 32:bind-libs-9.9.4-51.el7.x86_64 already installed and latest version
wrote key file "/etc/rndc.key"
Created symlink from /etc/systemd/system/multi-user.target.wants/named.service to /usr/lib/systemd/system/named.service.

-- Installing and configuring cron tasks
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version

-- Configuring phpMyAdmin

-- Configuring Roundcube

-- Configuring Webalizer

-- Configuring Sentora

> New server crypto key written to cnf/security.php
> New API key has been generated!
> Account password for 'zadmin' has been updated!

Daemon is now running... (21:18 21st Oct 2017 IST)

START Apache Config Hook.
Apache Admin module ENABLED...
Apache Config has changed...
Backing up Apache Config to: /var/sentora/backups/
Apache VHost backups are enabled... Backing up current vhost.conf to: /var/sentora/backups/
Apache VHost purges are enabled... Purging backups older than: 7 days...
[FILE][PURGE_DATE][FILE_DATE][ACTION]
VHOST_BACKUP_1508600936 - 7 - 0 - Skipping file...
Purging old backups complete...
Apache backups complete...
Begin writing Apache Config to: /etc/sentora/configs/apache/httpd-vhosts.conf
Finished writting Apache Config... Now reloading Apache...
job 1 at Sat Oct 21 15:48:00 2017
Apache reload suceeded.
END Apache Config Hook.

START DNS Manager Hook
DNS Manager module ENABLED...
DNS Records have not changed...nothing to do.
END DNS Manager Hook.

START MySQL Databases hook
Calculating the total size of all MySQL databases....
END MySQL Databases hook

START Calculating disk Usage for all client accounts..
Disk usage for user "zadmin" is: 0 (0 bytes)
END Calculating disk usage

START Calculating bandwidth usage for all client accounts..
END Calculating bandwidth usage

BEGIN Webalizer Stats
Generating webalizer stats html...
END Webalizer Stats

START Backup Config.
Backup Config module ENABLED...

Backup Purging enabled - Purging backups older than 30 days...
[FILE][PURGE_DATE][FILE_DATE][ACTION]
Backup Purging COMPLETE...

Purging backups from temp folder...
[FILE][PURGE_DATE][FILE_DATE][ACTION]
END Backup Config.

START Sentora Updates hook
Checking for latest version of Sentora...
END Sentora Updates hook

START checking for any avaliable module updates..
Checking update for mod: Aliases
Checking update for mod: Apache Config
Checking update for mod: Backup
Checking update for mod: Backup Config
Checking update for mod: Change Password
Checking update for mod: Client Notice Manager
Checking update for mod: Cron Manager
Checking update for mod: Distribution Lists
Checking update for mod: DNS Config
Checking update for mod: DNS Manager
Checking update for mod: Domains
Checking update for mod: FAQ's
Checking update for mod: Forwards
Checking update for mod: FTP Accounts
Checking update for mod: FTP Config
Checking update for mod: Mail Config
Checking update for mod: Mailboxes
Checking update for mod: Manage Clients
Checking update for mod: Manage Groups
Checking update for mod: Module Admin
Checking update for mod: My Account
Checking update for mod: MySQL Database
Checking update for mod: MySQL Users
Checking update for mod: Package Manager
Checking update for mod: Parked Domains
Checking update for mod: PHPInfo
Checking update for mod: phpMyAdmin
Checking update for mod: phpSysInfo
Checking update for mod: Protected Directories
Checking update for mod: Sentora Config
Checking update for mod: Sentora News
Checking update for mod: Service Status
Checking update for mod: Shadowing
Checking update for mod: Sub Domains
Checking update for mod: Theme Manager
Checking update for mod: Updates
Checking update for mod: Usage Viewer
Checking update for mod: Webalizer Stats
Checking update for mod: WebMail
END getting module version update information!

Daemon run complete! (21:19 21st Oct 2017 IST)
install: line 1161: chattr: command not found
Restarting mariadb
Restarting httpd
Restarting postfix
Restarting dovecot
Restarting crond
Restarting named
Restarting proftpd
Restarting atd
########################################################
 Congratulations Sentora has now been installed on your
 server. Please review the log file left in /root/ for
 any errors encountered during installation.`

**Comment by Ron-e** [comment]
The installers are on a separate repository -> https://github.com/sentora/sentora-installers
Also it looks like you are using fedora which isn't officially supported-> http://docs.sentora.org/?node=7
