### ISSUE TITLE
Typo in "The domain already appears to exsist on this server."

### ISSUE THREAD

**Issue by skyleet** [sentora/sentora-core#312]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this 
![screenshot 10](https://user-images.githubusercontent.com/11787352/32899193-4cea4622-cb10-11e7-9b95-0d45ac8a40dd.png)
issue tracker for support.

For bug reports please provide the following information:

Operating System: ubuntu 14.04

Operating System Version number:

Sentora Version: latest

Issue:

How to reproduce it:

Suggested fix or solution if you have any:

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
Fixed.
