### ISSUE TITLE
"Show/Hide Password" in ftp accounts does nothing.

### ISSUE THREAD

**Issue by skyleet** [sentora/sentora-core#313]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System: Win10 FCU

Operating System Version number:

Sentora Version: latest

Issue:

How to reproduce it:

Suggested fix or solution if you have any:

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
Works fine for me with default theme. Are you using a different or custom theme? If so, the js may not be properly included if at all.

**Comment by JamesKingdom** [comment]
I'm having the same problem using `S-Type` - Is there anyway you can update this theme with the hide password JS in?

**Comment by Ron-e** [comment]
> I'm having the same problem using S-Type - Is there anyway you can update this theme with the hide password JS in?

 S-Type has his own repo on github -> https://github.com/auxio/S-Type
Are you using the latest version? 
which browser are you using?
Because on my install it works..

**Comment by Ron-e** [comment]
@skyleet are you using MarkDark windows version of Sentora?
He has edited the themes himself and you have to ask him..
Although he is not very active with updates.
