### ISSUE TITLE
Error add domain xyz.name.vn

### ISSUE THREAD

**Issue by cunghoc** [sentora/sentora-core#314]
I not add domain xyz.name.vn. System notice: "You cannot add a Sub-Domain here. Please use the Subdomain manager to add Sub-Domains."
How to do add domain here?

**Comment by chongma** [comment]
add name.vn as a domain.  then edit the dns records and add xyz.name.vn as an a or cname record.  then add xyz.name.vn in the subdomains section

**Comment by cunghoc** [comment]
Thanks chongma for reply but only one user add domain .name.vn. If multiple users add domain .name.vn then how to do?

**Comment by chongma** [comment]
i remember someone asking this in the forum or maybe in an issue.  i don't think it is possible at the moment.  the domain can only be controlled by one customer.  can cPanel do this?

**Comment by cunghoc** [comment]
Yes, one domain use by one customer. I think .name more than 3 characters then Sentora think it is a domain. Error is tech Sentora (Sorry, I can't speak English well)

**Comment by TGates71** [comment]
You must add name.vn as a shared domain so others can use it also. name.vn is not a valid .tld 
http://docs.sentora.org/?node=100
