### ISSUE TITLE
Backups not working correctly

### ISSUE THREAD

**Issue by MoBadawy** [sentora/sentora-core#315]
Operating System: CentOS

Operating System Version number: 6.9

Sentora Version: 1.0.3

Issue:
I found 2 problems in the backup.
First: after backup finished, it doesn't move to "user/backup" it stay in tmp and you can download it via link anyway.

Second: It doesn't backup the databases just the files.

**Comment by MBlagui** [comment]
The backup never offered DB's backup. 

I have a script that do it already.

Also the manual backup was already disabled since a while.
