### ISSUE TITLE
Dns Problem

### ISSUE THREAD

**Issue by imtiaza26** [sentora/sentora-core#316]
I am getting error after changing dns records + its not adding the records in dns when the domain is added

After i run php -f /etc/sentora/panel/bin/daemon.php
I am getting these logs

``[root@2` bind]# php -f /etc/sentora/panel/bin/daemon.php
Daemon is now running... (23:36 17th Jan 2018 PKT)

START Apache Config Hook.
Apache Admin module ENABLED...
Apache Config has NOT changed...nothing to do.
END Apache Config Hook.

START DNS Manager Hook
DNS Manager module ENABLED...
DNS Records have changed... Writing new/updated records...
Updating /etc/sentora/configs/bind/etc/named.conf
CHECKING ZONE FILE: /etc/sentora/configs/bind/zones/alrehmantrust.org.txt...
zone alrehmantrust.org/IN: loading from master file /etc/sentora/configs/bind/zones/alrehmantrust.org.txt failed: file not found
zone alrehmantrust.org/IN: not loaded due to errors.
Syntax ERROR. Skipping zone record.
CHECKING ZONE FILE: /etc/sentora/configs/bind/zones/jobshop.ami-gears.com.txt...
zone jobshop.ami-gears.com/IN: loading from master file /etc/sentora/configs/bind/zones/jobshop.ami-gears.com.txt failed: file not found
zone jobshop.ami-gears.com/IN: not loaded due to errors.
Syntax ERROR. Skipping zone record.
CHECKING ZONE FILE: /etc/sentora/configs/bind/zones/smartspace.asia.txt...
zone smartspace.asia/IN: loading from master file /etc/sentora/configs/bind/zones/smartspace.asia.txt failed: file not found
zone smartspace.asia/IN: not loaded due to errors.
Syntax ERROR. Skipping zone record.
Reloading BIND now...
job 30 at 2018-01-17 23:36
END DNS Manager Hook.

START MySQL Databases hook
Calculating the total size of all MySQL databases....
END MySQL Databases hook

START Calculating disk Usage for all client accounts..
Disk usage for user "zadmin" is: 149940 (146.4 KB)
Disk usage for user "imran" is: 541152421 (528.5 MB)
Disk usage for user "smartspace" is: 32105463 (31.4 MB)
END Calculating disk usage

START Calculating bandwidth usage for all client accounts..
Processing domain "alrehmantrust.org"
Generating bandwidth..
usage: 0 (0 bytes)
No bandwidth used, skipping!
Processing domain "ami-gears.com"
Generating bandwidth..
usage: 0 (0 bytes)
No bandwidth used, skipping!
Processing domain "jobshop.ami-gears.com"
Generating bandwidth..
usage: 0 (0 bytes)
No bandwidth used, skipping!
Processing domain "smartspace.asia"
Generating bandwidth..
usage: 0 (0 bytes)
No bandwidth used, skipping!
END Calculating bandwidth usage

BEGIN Webalizer Stats
Generating webalizer stats html...
Generating stats for: zadmin/alrehmantrust.org
Webalizer V2.21-02 (Linux 2.6.32-042stab127.2 x86_64) English
Using logfile /var/sentora/logs/domains/zadmin/alrehmantrust.org-access.log (clf)
Creating output in /etc/sentora/panel/modules/webalizer_stats/stats/zadmin/alrehmantrust.org
Hostname for reports is '2'
History file not found...
No valid records found!
Failed
Generating stats for: imran/ami-gears.com
Webalizer V2.21-02 (Linux 2.6.32-042stab127.2 x86_64) English
Using logfile /var/sentora/logs/domains/imran/ami-gears.com-access.log (clf)
Creating output in /etc/sentora/panel/modules/webalizer_stats/stats/imran/ami-gears.com
Hostname for reports is '2'
Reading history file... webalizer.hist
Generating report for January 2018
Saving history information...
Generating summary report
4628 records in 1 seconds, 4628/sec
Succeeded
Generating stats for: imran/jobshop.ami-gears.com
Webalizer V2.21-02 (Linux 2.6.32-042stab127.2 x86_64) English
Using logfile /var/sentora/logs/domains/imran/jobshop.ami-gears.com-access.log (clf)
Creating output in /etc/sentora/panel/modules/webalizer_stats/stats/imran/jobshop.ami-gears.com
Hostname for reports is '2'
History file not found...
No valid records found!
Failed
Generating stats for: smartspace/smartspace.asia
Webalizer V2.21-02 (Linux 2.6.32-042stab127.2 x86_64) English
Using logfile /var/sentora/logs/domains/smartspace/smartspace.asia-access.log (clf)
Creating output in /etc/sentora/panel/modules/webalizer_stats/stats/smartspace/smartspace.asia
Hostname for reports is '2'
Reading history file... webalizer.hist
Generating report for January 2018
Saving history information...
Generating summary report
48 records in 1 seconds, 48/sec
Succeeded
END Webalizer Stats

Daemon run complete! (23:36 17th Jan 2018``

>

**Comment by Ron-e** [comment]
looks like you have a Syntax ERROR, you can better ask this on the forum as this looks like a user mistake.
DNS support -> http://forums.sentora.org/forumdisplay.php?fid=34
