### ISSUE TITLE
Redirecting

### ISSUE THREAD

**Issue by RayTrix** [sentora/sentora-core#317]
Hello
Every time i open the browser and want to go on some sites, there just opens ''Sentora Control panel'' I haven't installed Sentora before, Can't acces Steam or other apps

**Comment by PhilipMcGaw** [comment]
Where did you install it?

What machine are you browsing on?

How are these two computers related on your network?

**Comment by RayTrix** [comment]
Oh, sry, i didn't explain it right, I don't have Sentora installed, just write here, cuz it's the forum.

**Comment by Ron-e** [comment]
So, someone changed your browsers startup page to some random Sentora install?
By the way, this github is for issues like bugs, for other things go to the Sentora forum is there -> http://forums.sentora.org/

**Comment by RayTrix** [comment]
Not the startup page, it's only if I search for some sites, there shows this.
![sentora](https://user-images.githubusercontent.com/35555120/35110853-1d9dec0c-fc7a-11e7-9f9b-36ba99eb90eb.png)


I don't remember setting, downloading or installing anything. I tried so much things and none did work.

**Comment by PhilipMcGaw** [comment]
OS, Browser(s), website example addresses? Who else is on your network?

**Comment by RayTrix** [comment]
Win 7, browsing on Opera, tried google, on it i can't go anywhere. on Opera, i can at least visit some. Well, there are 2 other people connected, but noone is using Sentora. As i said before, i can't access steam, plug.dj and I'm sure i can find much more

**Comment by RayTrix** [comment]
Well sorry ... I am pice of .... I tried so much complicated things but didn't think of something like proxy, it's solved, thanks for your help. You can now close it
