### ISSUE TITLE
DocumentRoot httpd-vhosts.conf

### ISSUE THREAD

**Issue by nicdnepr** [sentora/sentora-core#318]
Operating System:
centos
Operating System Version number:
6
Sentora Version:
1.0.3
Issue:
cant change  DocumentRoot for domain
How to reproduce it:
open /etc/sentora/configs/apache/httpd-vhosts.conf  and change DocumentRoot 
but it resets to default after some time
Suggested fix or solution if you have any:

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
This is not a bug and is explained in our documentation here: http://docs.sentora.org/?node=104
