### ISSUE TITLE
Sentora Admin Console - Install SSL (CentOS)

### ISSUE THREAD

**Issue by jay-sam** [sentora/sentora-core#320]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System:
CentOS

Operating System Version number:
7.4

Sentora Version:
Sentora (1.0.3)

Issue:
"Configuration and Tutorials" / fix for SSL Config to Sentora Admin Console
https permenant redirect
vhost for 80 and 443
Forbidden: you don't have permission to access /
Control-M
Creating self-signed cert

How to reproduce it:
NA

Suggested fix or solution if you have any:
See attached doc
[sentora-admin_SSL.txt](https://github.com/sentora/sentora-core/files/1985394/sentora-admin_SSL.txt)

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
What is this? What is the actual issue and what are you trying to fix?

**Comment by jay-sam** [comment]
My apologies,

This was meant to be a documentation up. I did not realize until after posting that there was an option for that in Documentation on your site.

 

The purpose was to match and ease end-user configuration challenges for the Ubuntu SSL,  and CentOS SSL deployments for Admin Console.

 

Then the noted Control-M issue when updating Global Entry from apache config module.

Outdated SSLv3

And deprecated nameVirtualHost value with apache 2.4

And adding to eliminate any Forbidden 403 access denied 

<Directory "/etc/sentora/panel/">

    Options +FollowSymLinks -Indexes

    AllowOverride All

    Require all granted

</Directory>

 

So with the config values that I send the end-user could simple just add it to the Global entry with minimal changes, just to the cert, key and hostname.

 

Thanks,

Jay
