### ISSUE TITLE
DNS DKIM TXT record

### ISSUE THREAD

**Issue by chongma** [sentora/sentora-core#321]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System:
CentOS 7

Operating System Version number:
centos-release-7-5.1804.el7.centos.x86_64

Sentora Version:
1.0.3

Issue:
there is no way to add an OpenDKIM record to DNS similar to this plesk issue https://support.plesk.com/hc/en-us/articles/115002551549-Unable-to-start-BIND-named-dns-rdata-fromtext-syntax-error-

How to reproduce it:
i am trying to add this text record as given to me by OpenDKIM but it seems impossible
nbmlaw.co.uk.dkim._domainkey	IN	TXT	( "v=DKIM1; k=rsa; "
	  "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwjUG8LCZ8vrqi+2aD1a9KPHFLGA2+jAjPYc/xu/SVRgY3bbj6s1vVUZDPMDnuRqISkjJ/0AutQAxRYx2g82CDB9E8Y+8Py25mOAo6nlG4yyc843Ll+Uf1MLSNtqQavrL7AcQL21SDcQejti0lzmxzDBNqQVWB96zJNtxvjSI4suDbkSsh7fsITXPAstj5fp+Uyjopd+aPGZ+FD"
	  "VT3Qf7/1nUcRzu/wNLBK+6j1nRp6wwIhLDojjIs1ipQuwWsirfrJ85fPdVb/gAZEL9q0Q8ih2vkj0j4m1CgOf1NytBbnyqj2ydr9Unp0HjyjWFR9TDkrC6uQEOyuQWpdkQ3VUDHQIDAQAB" )  ; ----- DKIM key nbmlaw.co.uk.dkim for nbmlaw.co.uk

Suggested fix or solution if you have any:
either support multiple TXT entries with the same host name or have bigger TXT fields which allow double quotes

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by chongma** [comment]
i also mentioned same issue on this thread http://forums.sentora.org/showthread.php?tid=586&pid=22983#pid22983

**Comment by chongma** [comment]
seems new version of opendkim uses a stronger algorithm. setting SignatureAlgorithm rsa-sha256 in 
/etc/opendkim.conf makes the file shorter. still needs to be solved though...

**Comment by fearworksmedia** [comment]
Please see my post here: http://forums.sentora.org/showthread.php?tid=586&pid=29801#pid29801
