### ISSUE TITLE
Mysql user information (password) stored in plain text in database

### ISSUE THREAD

**Issue by mcleanholmes** [sentora/sentora-core#326]
Operating System: Cent OS

Operating System Version number: 7

Sentora Version: 1.0.3

Issue: Mysql user information is stored in plain text in the database

How to reproduce it: look at the mysql user information table for Sentora.

Suggested fix or solution if you have any:

Introduce a global settings configuration that allows for a key and salt configuration to encrypt and decrypt information that is sensitive.

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
Do you mean to have all information encrypted? Will reopen if you mean something different.
