### ISSUE TITLE
Can Install Sentora Without Bash ?

### ISSUE THREAD

**Issue by desawarna** [sentora/sentora-core#328]
I have uploaded the sentora_core to htdocs,

and already created a database then imported sql  , sql from https://raw.githubusercontent.com/sentora/sentora-installers/master/preconf/sentora-install/sql/sentora_core.sql

then edit the configuration in sentora / cnf / db.php

Can Install Sentora Without Bash ?

**Comment by TGates71** [comment]
No, not really. There is a LOT of configurations in the bash file. Also, you can not install Sentora on a server that already has mysql, php, apache, etc. Sentora installs all of this for you and configures it.
For more information regarding installation and packages Sentora installs, view our Docs: http://docs.sentora.org/?node=19

**Comment by desawarna** [comment]
Okay thanks mr. @Tgates71
