### ISSUE TITLE
[Module] ftp_management broken

### ISSUE THREAD

**Issue by Bizarrus** [sentora/sentora-core#333]
CentOS 7.1, Sentora 1.3

On **module.zpm** vou have an condition: `<% if isDeleteFTP %>` but the method expects an **argument**: `static function getisDeleteFTP($uid){`

> ArgumentCountError: Too few arguments to function module_controller::getisDeleteFTP(), 0 passed in /etc/sentora/panel/etc/tmp/storage/Sentora_Default/aa36931e2226d9a6ed8598d4d6c73213.cache on line 271 and exactly 1 expected in /etc/sentora/panel/modules/ftp_management/code/controller.ext.php on line 397

**Comment by TGates71** [comment]
Fixed? @Dukecitysolutions

**Comment by Dukecitysolutions** [comment]
Needs more testing. I can't replicate or reproduce the error in Sentora v2. Is anyone else experiencing this error or issue???

**Comment by TGates71** [comment]
No errors noticed in v2 after deleting ftp accounts.
