### ISSUE TITLE
Support for individual account configuration files

### ISSUE THREAD

**Issue by bradjtrammell** [sentora/sentora-core#335]
This is more of a feature request, than an issue. But it's a much needed feature in my opinion. An issue I'm running into more often than not is that a user has several subdomains and one large configuration file is hard, and even annoying at times to navigate. Why not set up Sentora to automatically just generate a configuration file for that user, and have all the domains stored there, or even one for the users primary domain, and then one for all subdomains, like:

www.example.com > /etc/sentora/configs/apache/domains/example_com.conf
img.example.com > /etc/sentora/configs/apache/subdomains/example_com.conf

At least from my point of view, this is much easier to manage from a command line perspective, and having each account separated by the account owner, rather than one gigantic file.

I can't imagine this would be too hard to accomplish, the panel should just be able to pass a few parameters off to indicate what user made the change, and append or ammend the affected file.

Worse case scenario, give the server owner, the option for combined configuration files (like they are now), or ones that are more organized and laid out. Not everyone likes to "command line it", however as a person who's got 5 Sentora installations, it's a massive PITA to manage the configuration file, especially since Sentora does not support SSL natively in the panel without a module, or VHOST configuration. We need an option to automatically generate and assign Lets Encrypt certificates for domains created, or for subdomains (or if you are feeling squirrelly, wildcards)

**Comment by TGates71** [comment]
You mean separate vhost files for each domain?
Also, my sencrypt module (ssl management) will be a core module in the next release! V2.0.1 i believe.

**Comment by Dukecitysolutions** [comment]
Closing for now.
