### ISSUE TITLE
Showing FTP port 21 is closed In Service status- FTP logins not working

### ISSUE THREAD

**Issue by NavneetSinghTom** [sentora/sentora-core#336]
For support, please use our forums: http://forums.sentora.org/, you can search for solutions there.
Feel free to open a new question if none of the threads solve your problem.
Please, do NOT use this issue tracker for support.

For bug reports please provide the following information:

Operating System: Centos

Operating System Version number: 7.6

Sentora Version: 1.0.3

Issue: FTP access denied, showing post 21 is closed for FTP under service status

How to reproduce it: Need help

Suggested fix or solution if you have any: need help

Thank you on the behalf of the Sentora Team.

V 0.0.2

**Comment by TGates71** [comment]
For support, please use our forums: http://forums.sentora.org/,
