### ISSUE TITLE
another bug, critical, remote root

### ISSUE THREAD

**Issue by VedranIteh** [sentora/sentora-core#345]
tip: updater scripts should delete zsudo 

**Description**
Unfiltered $username variable is included in many exec functions all around different modules. Which is a bug for itself. 

**Example**

1. Obtain root sql password with dns_admin bug. 
2. Change someones username to a command you want to execute.
3. Run for e.g. vulnerable backup module to execute it
4. repeat steps 2 and 3 until using zsudo script you don't get yourself a superuser or add yourself to sudoers

@anyonewhoevencares

**Comment by TGates71** [comment]
Bump. @Dukecitysolutions fixed in v2?

**Comment by Dukecitysolutions** [comment]
Fixed. Closing.
