### ISSUE TITLE
[Solved] backup download error 500

### ISSUE THREAD

**Issue by motz182** [sentora/sentora-core#348]
Hello friends, for everyone who has a problem downloading bakups I found a random solution to work around the problem.
first I created a folder called "Backups" in this location /etc/sentora/panel/var/sentora/backups
then you need to update the /etc/sentora/panel/modules/backupmgr/code/dobackup.php file
you just need to copy the file and replace it.

https://gist.github.com/motz182/761d2f9bc3887aa32fecc831bd697d7f

Sorry if my english is bad, as this was a google translation.
I am Brazilian.

**Comment by TGates71** [comment]
backup and download appear to be working in v2.0.0
