### ISSUE TITLE
Debian 10 "Buster" is here

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#349]
Debian 10 "Buster" is here:
- https://www.debian.org/News/2019/20190706

**Comment by Dukecitysolutions** [comment]
We are preparing to support this OS system very soon. We need some time to organize and get a stable solution available to the public. Thank you for your support.

**Comment by andykimpe** [comment]
have already said sentora is not compatible with php 7 may suhosin is not available for this version except on debian 10 it is php 7 which and install

until this problem is solved there is no need to request the addition of other operating systems

because this one cannot be offered

**Comment by Neustradamus** [comment]
About PHP: https://www.php.net/supported-versions.php

Currently the minimum PHP supported must be 7.2.x.

**Comment by TGates71** [comment]
V2 supports php7.2+

**Comment by Neustradamus** [comment]
@TGates71: The Debian 10 support has been added?

Debian 11 too?

**Comment by Neustradamus** [comment]
@TGates71: Please reopen this ticket!

**Comment by Dukecitysolutions** [comment]
We will hopefully be supporting Debian again soon. We are focusing on securing and making Sentora stable with PHP 7+ currently.

**Comment by TGates71** [comment]
Newer Debian released and posted. closing this issue.
