### ISSUE TITLE
Ubuntu 20.04 "Focal Fossa" LTS is here

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#350]
Ubuntu 20.04 "Focal Fossa" LTS is here:
- https://ubuntu.com/blog/ubuntu-20-04-lts-arrives

**Comment by Dukecitysolutions** [comment]
We are preparing to support this OS system very soon. We need some time to organize and get a stable solution available to the public. Thank you for your support.

**Comment by DemOnJR** [comment]
i use ubuntu 20.04 too

**Comment by andykimpe** [comment]
ubuntu 20.04 is still in its first version even canonical strongly recommends not to install the new lts before the release of LTS + 2 in other words it and better to wait for 20.04.2 before offering it

**Comment by gusarg81** [comment]
Hi, I am trying to find a replacement for i-MSCP (since does not support Ubuntu 20.04 either). Any news about this with Sentora? Thanks.

**Comment by Neustradamus** [comment]
@TGates71: The support has been added?

**Comment by TGates71** [comment]
@Neustradamus yes, sentora supports Ubuntu 22.04

**Comment by Neustradamus** [comment]
Who has tested?

**Comment by Neustradamus** [comment]
Sentora v2.0.0 RELEASED!
http://forums.sentora.org/showthread.php?tid=12920

```
Great news gang! The long awaited new Sentora v2.0.0 with php 7 is now available!

This release requires your server to be running Ubuntu 20.04 or CentOS 8.

Visit our installation docs: http://docs.sentora.org/index.php?node=22
```
