### ISSUE TITLE
CentOS 8.x is here

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#351]
CentOS 8.x is here
- https://www.centos.org/

**Comment by Rakhmanov** [comment]
That does not take Nostradamus to know.

**Comment by Dukecitysolutions** [comment]
We are preparing to support this OS system very soon. We need some time to organize and get a stable solution available to the public. Thank you for your support.

**Comment by andykimpe** [comment]
have already said sentora is not compatible with php 7 may suhosin is not available for this version except on centos 8 it is php 7 which and install

until this problem is solved there is no need to request the addition of other operating systems

because this one cannot be offered

**Comment by Neustradamus** [comment]
About PHP: https://www.php.net/supported-versions.php

Currently the minimum PHP supported must be 7.2.x.

**Comment by Lokesh2511234** [comment]
minimum PHP supported must be 7.2.x.,,, [Power BI Traiing](https://igmguru.com/data-science-bi/power-bi-certification-training/)

**Comment by maverick85** [comment]
Suhosin is not available nor needed on PHP 7. Suhosin is a dead and buried project.
PHP7 has been around for half a decade.

We've been using Virtualmin for long, looking to test some alternatives to test and implement. We donate to projects that are up to speed with the reality, it was quite a shame seeing that this software/project is still dealing with such retrograde issues.

**Comment by MBlagui** [comment]
Centos is dead as Redhat killed it. Unless we move to centos streams.

**Comment by maverick85** [comment]
Oracle Linux is free and we've shifted most of our servers to it.
We're also using the new Red Hat free subscription for up to 16 production servers for some core services.

**Comment by Neustradamus** [comment]
I have done a ticket about Rocky Linux 8.4:
- https://github.com/sentora/sentora-core/issues/356

**Comment by maverick85** [comment]
Hi @Neustradamus, I tried to install Sentora on AlmaLinux (the CentOS derivative from CloudLinux) which is actually very targeted to web servers (since its now the default OS for cPanel/WHM).

I got this:
```
[root@web-al0 ~]# bash <(curl -L -Ss http://sentora.org/install)

############################################################
#  Welcome to the Official Sentora Installer 1.0.3  #
############################################################

Checking that minimal requirements are ok
Detected : CentOs  8  x86_64
Sorry, this OS is not supported by Sentora.
```

**Comment by Neustradamus** [comment]
@maverick85: It has been solved?

**Comment by maverick85** [comment]
As far as my knowledge goes, no, but haven't checked in a while.

**Comment by Neustradamus** [comment]
This ticket must be reopened!

**Comment by Neustradamus** [comment]
Sentora v2.0.0 RELEASED!
http://forums.sentora.org/showthread.php?tid=12920

```
Great news gang! The long awaited new Sentora v2.0.0 with php 7 is now available!

This release requires your server to be running Ubuntu 20.04 or CentOS 8.

Visit our installation docs: http://docs.sentora.org/index.php?node=22
```
