### ISSUE TITLE
FTP Accounts

### ISSUE THREAD

**Issue by gbrain2001** [sentora/sentora-core#354]
FTP Accounts does not show Create an FTP user

1. Go to 'File Management'
2. Click on 'FTP Accounts'

**Expected behavior**
The page should load with the module to Create the ftp account.

The file is missing js/popover.js. there is no link to the javascript.

**Server info (please complete the following information):**
 - OS: [CentOS 7]
 - Sentora BUILD version: Build-1.0.3

**Additional context**
When I am on the module page: ftp_management, I cannot click on the menu items.

**Comment by TGates71** [comment]
Ftp account name is ftp user name. Possible bug in OP installation.
