### ISSUE TITLE
Debian 11 "Bullseye" Full Freeze starts

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#355]
Debian 11 "Bullseye" Full Freeze starts:
- https://lists.debian.org/debian-devel-announce/2021/06/msg00000.html

**Comment by Dukecitysolutions** [comment]
We will hopefully be supporting Debian again soon. We are focusing on securing and making Sentora stable with PHP 7+ currently.

**Comment by TGates71** [comment]
Newer Debian released and posted. closing this issue.
