### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [sentora/sentora-core#357]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by TGates71** [comment]
Ok. I will check into adding the security. Md file. We do know there are
some security issues and we have been working on them.
You can safely report it here to me and I will forward it to the dev team.
Thank you for testing and helping us continue continue Sentora.

**Comment by zidingz** [comment]
Thanks! If it'll save you time: https://github.com/sentora/sentora-core/pull/358

**Comment by TGates71** [comment]
Thanks!
