### ISSUE TITLE
More illuminating web presence

### ISSUE THREAD

**Issue by xeruf** [sentora/sentora-core#363]
Currently, sentora.org has no technical list of features, it does not provide HTTPS (come on!) and no screenshots.

We are currently using the proprietary LiveConfig and would be happy to migrate to an open-source solution if it proves sufficient for us, including proper financial support. But I have found no substantial documentation, making it hard to find out what Sentora actually provides...

**Comment by NigelNapier** [comment]
You've checked out docs.sentora.org?

Sentora does support SSL, it's just not a core module yet.

**Comment by TGates71** [comment]
Available in v2
