### ISSUE TITLE
Is sentora dead?

### ISSUE THREAD

**Issue by rajeevrrs** [sentora/sentora-core#365]
No more updates and upgrades? 

Sentora development discontinued?

**Comment by Ron-e** [comment]
Simply said yes.
but there is a beta (http://forums.sentora.org/showthread.php?tid=12794&pid=33963) but before it's release it's already out of date.
I am switching to https://hestiacp.com/ i can not wait any longer.

**Comment by TGates71** [comment]
V2.0.0 is finally ready!

**Comment by rajeevrrs** [comment]
@TGates71 when it will be released?

**Comment by TGates71** [comment]
The new v2 core files are here: https://github.com/sentora/sentora-core/tree/2.0.0
The installer has been updated to use this repo.

**Comment by rajeevrrs** [comment]
@TGates71 

`bash <(curl -L -Ss http://sentora.org/install)`

This will install new version Sentora 2.0? 

Does 2.0 also support PHP 8.X?

**Comment by TGates71** [comment]
Yes, No to php 8. Use the forums for questions or help. Github is for tracing bugs, fixes and all coding issues.
