### ISSUE TITLE
Debian 12 "Bookworm" Freeze

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#372]
Debian 12 "Bookworm" Freeze:
- https://release.debian.org/bookworm/freeze_policy.html

**Comment by Dukecitysolutions** [comment]
We will hopefully be supporting Debian again soon. We are focusing on securing and making Sentora stable with PHP 7+ currently.

**Comment by Neustradamus** [comment]
Debian 12 has been released:
- https://www.debian.org/News/2023/20230610

**Comment by Dukecitysolutions** [comment]
Supporting soon. Closing.
