### ISSUE TITLE
Master branch is not up-to-date and by default

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#373]
Dear @sentora team,

In first, I wish you a Happy New Year!

Can you update the master branch and use it by default?
- https://github.com/sentora/sentora-core/tree/master

Can you add all the code in master branch with historical builds?
Last one is 1.0.1.

There are several branches, it is possible to clean it?
- https://github.com/sentora/sentora-core/branches/all

**Comment by Dukecitysolutions** [comment]
@Neustradamus The master has been defaulted back. The master branch is our current work in progress (BETA). As the code is tested/verified and working properly, we then make a stable branch to release. This is the way Sentora has always done this and is built into our installers.
