### ISSUE TITLE
Tags and releases problems

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-core#374]
Dear @sentora team,

There is a problem of tags and releases:
- Last is beta-1.0.4: https://github.com/sentora/sentora-core/tags
- Last is 1.0.1: https://github.com/sentora/sentora-core/releases

Can you solve it?

**Comment by Neustradamus** [comment]
And missing versions:
- 1.0.3 vs 1.0.3-bugfixes (2 versions?)
- 1.0.4

**Comment by TGates71** [comment]
We are working to sort github out with the proper tags/master.

**Comment by TGates71** [comment]
This should be sorted out now? @Neustradamus can you confirm?

**Comment by Neustradamus** [comment]
@TGates71: Always same...
- https://github.com/sentora/sentora-core/tags
- https://github.com/sentora/sentora-core/releases

Same here:
- https://github.com/sentora/sentora-installers/tags
- https://github.com/sentora/sentora-installers/releases

**Comment by Dukecitysolutions** [comment]
Thank you we are fixing this. Closing.
