### ISSUE TITLE
Sentora.org forum not sending activation email

### ISSUE THREAD

**Issue by mhoek2** [sentora/sentora-core#381]
Hello @sentora

**Describe the bug**
I created an account on the forum, however I never received the activation email.
Nor is it marked as spam
I have also tried the [Resend activation form](https://forums.sentora.org/member.php?action=resendactivation)

**Expected behavior**
Recieive the activation email

@TGates71 sorry to tag you, but I can't contact you through the forum.

**Comment by TGates71** [comment]
We will look into this and get back to you as soon as possible. Sorry for
the inconvenience.
-TGates

**Comment by TGates71** [comment]
Sorry for the late reply. What is the email you used to apply?

**Comment by mhoek2** [comment]
jksunny71@hotmail.com and the username should speak for itself when you see it.

No, I still have no email. perhaps I misspelled it?

**Comment by TGates71** [comment]
I'm not sure why you didn't get the email, but I activated your account.

**Comment by Dukecitysolutions** [comment]
More of a forums places for this. Closing.

**Comment by mhoek2** [comment]
> More of a forums places for this. Closing.

I don't want to be rude, however, I couldn't post on the forum because my account was not activated.

**Comment by Dukecitysolutions** [comment]
I’m sorry to hear that. I’m glad we were able to get your account active. I now see that in the post. Thank you for contacting us with any issues you may have.
