### ISSUE TITLE
i installed setastico and install wordpress after i active cdn cloudflare not work . i not can login in site and login my admin panel .

### ISSUE THREAD

**Issue by xspyapp** [sentora/sentora-core#387]
i installed setastico and install wordpress after i active cdn cloudflare not work . i not can login in site and login my admin panel .
and i not can install ssl in my domian

**Comment by TGates71** [comment]
From the information provided, this does not appear to be a Sentora or Sentastico issue. (Or even a WordPress issue.) You said you installed WordPress 'then activated cdn'. Whatever cdn you used seems to have messed up your dns and/or cloudflare. Start looking there to solve your problem.

**Comment by xspyapp** [comment]
Oops! Something went wrong. Your Lets Encrypt certificate was not created. Check if your website is LIVE. ERROR! -

**Comment by TGates71** [comment]
If your DNS setup is not working properly, then Sencrypt will not work either.
Please use our forums for support. This is for bug tracking only. Https://forums.sentora.org

**Comment by TGates71** [comment]
Just got home from work, I do not have telegram. Facebook messenger? Or email your info to me. tgates71@gmail.com
