### ISSUE TITLE
Oops! Something went wrong. Your Lets Encrypt certificate was not created. Check if your website is LIVE. ERROR! -

### ISSUE THREAD

**Issue by xspyapp** [sentora/sentora-core#388]
if you have telegram send me DM my id : @drsardin

Oops! Something went wrong. Your Lets Encrypt certificate was not created. Check if your website is LIVE. ERROR! -

**Comment by TGates71** [comment]
Continue this here: https://github.com/sentora/sentora-core/issues/387

**Comment by xspyapp** [comment]
> Continue this here: #387

i sended to your email
