### ISSUE TITLE
DNS Manager: ipv6 AAAA records cannot be added to match existing A records

### ISSUE THREAD

**Issue by trs998** [sentora/sentora-core#49]
If I have a A record for a host name, I cannot add a AAAA record with the same name

ERROR DNS NOT SAVED
Hostnames must be unique.

Suggested fix: DNS record verification modified to ensure only CNAME records must not name-collide with A or AAAA records. All other records of different type but the same name are valid (TXT record could be named the same as a A or CNAME, for example)

Currently blocking ipv6 handling on the DNS server.

**Comment by michelsup** [comment]
This bug keep firing with 1.0.0 version.

**Comment by MBlagui** [comment]
yep still there

**Comment by michelsup** [comment]
I made a pull request solving this issue, but I do not believe it will be reviewed quickly, unfortunately.

**Comment by bobsta63** [comment]
Code reviewed - I've merged the changes - Sorry just been busy the last week!
