### ISSUE TITLE
Bug in centos 6 cron job

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-core#51]
https://github.com/sentora/sentora-core/blob/master/etc/build/config_packs/centos_6/cron/zdaemon

This is buggy as you can see calls php55 that's wrong and to avoid any issue better we call cron

php /etc/zpanel/panel/bin/daemon.php to avoid any issues.

CRON IS NOT RUNNING as the patch in cron job is WRONG. Run it manually ( disable the output redirection and enjoy the FILE NOT FOUND).

M B

**Comment by ofirattia** [comment]
Hi, see this issue I closed maybe it will help you.
https://github.com/sentora/sentora-core/issues/151
