### ISSUE TITLE
sub domains limit/conflict (bug)

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-core#62]
Hi,

It happen often that I setup hosting for test.domain.com as a full hosting while domain.com not configure here. so the only way is to add as MAIN domain.

Then when I try to add test2.domain.com it will say only way is using sub domains. BUT sub domains allow only *.test.domain.com.

This will mean I need to be forced to setup the upper level domain while I don't use it so I can unlock all subdomains?

Take for com.tn we could allow less control if domain > 4 words? ( despite I have 2 word domains).

M B

**Comment by Edabio** [comment]
Tem uma falha na minha hospedagem ..., tento adicionar o dominio : importarrelogios.blog.br  e me aparece esta mensagem:
You cannot add a Sub-Domain here. Please use the Subdomain manager to add Sub-Domains.

O que fazer?

att.Edábio
Obrigado!

**Comment by TGates71** [comment]
The 'Shared Domain' feature in zadmin>Module Admin>Apache Config>Shared Domains should fix this.
