### ISSUE TITLE
Custom ports break api connection.

### ISSUE THREAD

**Issue by PS2Guy** [sentora/sentora-core#78]
If I decide to use a custom port for my Sentora installation then the api connection breaks.

Not sure how to work around this but just thought that I should report it to see if it can be fixed.

**Comment by bobsta63** [comment]
I can confirm that after testing this evening, I've set my development VM to use TCP port 81 for Sentora CP and then used one of the out-the-box products that utilises my XMWS library and all appears to work correctly (screenshots below):

![working_over_81_2](https://cloud.githubusercontent.com/assets/767628/5892853/17e2037a-a4c6-11e4-8928-a8322a835d29.png)
^ Sentora CP running on port 81

![working_over_81](https://cloud.githubusercontent.com/assets/767628/5892852/1496de02-a4c6-11e4-98c1-109cb5fff18c.png)
^ The API Client config being configured to conenct to port 81 and reporting services are 'up' and running fine.

Closing this 'issue' as it appears to have been fixed (testing using Sentora 'master' branch)
