### ISSUE TITLE
Can't create new DNS records.

### ISSUE THREAD

**Issue by PS2Guy** [sentora/sentora-core#86]
In DNs manager click on add new record and get redirected back to the dns manager home page with no option to create anew record.

Confirmed faulty on Ubuntu 14.04 and CentOS 7

**Comment by bobsta63** [comment]
After testing on the current developent branch today, I can confirm that this is definetly NOT broken in the standard release file, closing bug as no fix is required and appears that @Ron-e has fixed the bug and was part of one of his themes.

Therefore no core fix is required - closing this bug.

**Comment by kk86bioinfo** [comment]
I think this is still an issue for Safari, apparently the button should not use type="submit" if plan to apply javascript for inserting new record row. The correct way should use type="button" to allow the javascript to be applied. I tested in safari cannot add new record but firefox is fine.

**Comment by Ron-e** [comment]
@kk86bioinfo are you using a custom theme?

**Comment by kk86bioinfo** [comment]
Hi Ron-e, I recheck back today it is fine even in Safari. I am using default theme. I think I will just close this up by now.
