### ISSUE TITLE
Setting up a domain which contains a dash / hyphen gives an error

### ISSUE THREAD

**Issue by EdGoodall01** [sentora/sentora-core#91]
When adding the domain your-domain.co.uk, it says You cannot add a subdomain here. The domain isn't currently set up in any account, and I can add other domains with .co.uk

**Comment by MBlagui** [comment]
I was able to setup your-domain.co.uk & test.co.uk. You must have conflict in your setup or used the domain.

Unable to reproduce the bug.

**Comment by 5050** [comment]
Please read the doc : [Setting subdomain without domain](http://docs.sentora.org/index.php?node=50)
