### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by Amet13** [sentora/sentora-core#94]
Default panel (eng):
![screenshot-1](https://cloud.githubusercontent.com/assets/5184847/5423830/ab14c1a6-82e2-11e4-8578-8c5c3c9c86fb.png)
Panel, after russian language installation:
![screenshot](https://cloud.githubusercontent.com/assets/5184847/5423829/ab0f27a0-82e2-11e4-817c-13a34d71c6ae.png)

Can i fix them (menu on the second row)? This bug only when i am zadmin, if i use user profile all ok.
![screenshot-2](https://cloud.githubusercontent.com/assets/5184847/5423848/76d18fa8-82e4-11e4-9918-50864d34bc09.png)

P.S. Me and some people can help you with russian translations.
Thanks.

**Comment by MBlagui** [comment]
Seem the issue is related to menu's label too large to fit initial design limits... So solution increasing bar width or reduce menu labels? We can't adapt to each language with too large label. I don't think this should be fixed

**Comment by TGates71** [comment]
Technically, since it is using bootstrap, it should switch to a drop-down menu if the menu width is wider then the screen, obviously this isn't happening or coded into the menu properly.

**Comment by TGates71** [comment]
I will take a look at this this week.

**Comment by Amet13** [comment]
Maybe nedd rename "Домашняя" to "Дом" or use some webfont look like home.
"База данных" can changed to "БД".

**Comment by MBlagui** [comment]
You can rename them in languages files/DB it's not related to the core.

**Comment by apintocr** [comment]
@TGates71 , I do not believe Bootstrap should switch to a dropdown menu if the items are too big, it changes to dropdown when the screen is smaller, by default it has nothing to do with the items size.

**Comment by TGates71** [comment]
I see what you mean. Correct, the button/label name is too long. He needs to use something shorter.

**Comment by janoss** [comment]
Where to download Russian language?

**Comment by yanislavb** [comment]
I am sorry , but I need Russian translate for this panel. How I can find the translate file?

**Comment by Amet13** [comment]
yanislavb, привет.
Раньше можно было тут найти: http://www.zpanelcp.com/download/language-packs/ но сейчас видимо выпилили. Но у меня файлик в архивах остался, если интересно, то выложил его сюда: http://paste.ubuntu.com/12120806/
По идее все что требуется это допиливать этот файлик, я в свое время на примере немекцой локализации пробовал, но потом лень стало.

**Comment by yanislavb** [comment]
@Amet13 как я понял, там надо в какую то консоль или просто в MySQL? )

**Comment by Amet13** [comment]
Честно говоря не помню уже.

**Comment by yanislavb** [comment]
@Amet13 Если Вы еще при делах с Sentora, можете напомнить, как поменять язык, при условии, что все в БД было сделано идиально?

*когда увидел свой коммент годичной давности, слегка опешил*

**Comment by Amet13** [comment]
@yanislavb уже давно не при делах. Но помнится как-то гуглил.
