### ISSUE TITLE
Add Shadow button in Client Manager

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-core#96]
Just a tweak/feature request: Add a shadow button to the Client Manager module user list.
Just a matter of convenience. (of course, make a check to see if the shadow module is installed/enabled so it only shows if so)

**Comment by bobsta63** [comment]
I'll pick this up and implement over the weekend.

**Comment by TGates71** [comment]
cool deal1 :+1:

**Comment by TGates71** [comment]
Since it is a feature I will close it and add it our private task tracker and will look into this.

**Comment by TGates71** [comment]
Completed.
