### ISSUE TITLE
Bug: wrong open_basedir in cron tasks

### ISSUE THREAD

**Issue by rezaies** [sentora/sentora-core#98]
each time a user creates a cron task, the open_basedir for ALL cron tasks will change to the home directory of the user who created the last cron task.

for example, this is the output of crontab -e -u apache:
```
\# Cron ID: 1
... -d open_basedir="/var/sentora/hostdata/USER3/:/var/sentora/temp/" /var/sentora/hostdata/USER1/public_html/...
\# End Cron ID: 1
\# Cron ID: 2
... -d open_basedir="/var/sentora/hostdata/USER3/:/var/sentora/temp/" /var/sentora/hostdata/USER2/public_html/...
\# End Cron ID: 2
\# Cron ID: 3
... -d open_basedir="/var/sentora/hostdata/USER3/:/var/sentora/temp/" /var/sentora/hostdata/USER3/public_html/...
\# End Cron ID: 3
```

As you see the open_basedir for all the tasks is set to /var/sentora/hostdata/**USER3**/:

**Comment by MBlagui** [comment]
Checking

**Comment by bobsta63** [comment]
@rezaies can you confirm if you are running CentOS or Ubuntu?

**Comment by rezaies** [comment]
It's a CentOS 7
3.10.0-123.13.2.el7.x86_64

**Comment by bobsta63** [comment]
Ahhh ok, just wondred if this was in anyway related to #51

**Comment by MBlagui** [comment]
strange will check it too later on centos 6

**Comment by bobsta63** [comment]
I'll assign to you @MBlagui ok buddy... something to do with the Installers I'm sure!

**Comment by MBlagui** [comment]
Nope  #51  got fixed since a while. But I will check

**Comment by rezaies** [comment]
did you have the chance to check this?

**Comment by rezaies** [comment]
update: seems related to the presence of php-opcache module

**Comment by MBlagui** [comment]
caching or optimizing software can be an issue.

M B

**Comment by rothkj1022** [comment]
I've been running into this exact issue.  I only installed Sentora a month ago.  Did anyone find a solution or workaround for this?

**Comment by alnassre** [comment]
Still, the problem exists, using ubuntu 14.04

**Comment by alnassre** [comment]
Temporary solution: ubunru 14.04

#check the log to see the problem (where CRON to filter the lines)
grep CRON /var/log/syslog

#check the list of the cron you created
sudo crontab -u www-data -l

#also other way to check
cd /var/spool/cron/crontabs
cat www-data

#copy the code 
#edit in any text editor
# probably the problem on the USER999 is not currect with the line:
open_basedir="/var/sentora/hostdata/USER999/:/var/sentora/temp/" "

#paste it in the file using the command
crontab -e -u www-data

#or 
nano /var/spool/cron/crontabs/www-data

#restart command
service cron restart

#check the log (where CRON to filter the lines)
grep CRON /var/log/syslog

#may it take 5 min to refresh or force it with the restart command
