### ISSUE TITLE
Package module still show enable CGI

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-core#99]
Issue #1 CGI enable disable is still showing.

Issue #2 PHP enable / disable don't work as PHP for 2 reasons
vhost have ALWAYS php setting despite you disable php.
And most dangerous if you remove it from vhost (php related setup line), as php is enabled by default it would work without suhosin/open_basedir sandboxing ( tried when I remove manually php setup in vhost) 

Centos 6 hosts /etc/http/conf/php.conf that need to be removed & merged into panel config.

**Comment by TGates71** [comment]
I'll take a look at disabling the menu item until we can get a fix for it.

**Comment by bobsta63** [comment]
@MBlagui @TGates71 I've just pulled the code down to disable the 'Enable CGI' option however I can't seem to see it in the master branch? - You sure we don't just need to re-tag the release with these changes?

I don't see any trace of the 'Enable CGI' stuff here:-

https://github.com/sentora/sentora-core/blob/master/modules/packages/module.zpm
https://github.com/sentora/sentora-core/blob/master/modules/packages/code/controller.ext.php

Unless you are referring to another module but the Package Manager module code (linked above) doesn't appear to have anything in it!

I have also just checked the 1.0.0 branch and see that the code still remains there, so if the installer is still using the 'stable' branch (eg. 1.0.0) that is why  you probably still seeing that!

With regards to the CentOS HTTP Config, this in my opinion should be logged against the installer (to have the CentOS PHP.ini config removed at installation).

Bobby

**Comment by MBlagui** [comment]
When editing packages I still see enable CGI & enable PHP.

It's RC1 build here...

Also even if I disable PHP, I see that suhosin & openbasedir is setup & PHP WORKS... so looks ineffective.

**Comment by bobsta63** [comment]
Well you should see the 'Enable PHP' as that isn't to be disabled! - I cannot see how the hell you are seeing the Enable CGI when it is clearly not in the Package Manager module any more (I'm not joking, the links above I supplied clearly show that there isn't a check-box rendered for that option) - You sure you are referring to the Package module? - Can you upload a screenshot?

The disablement of suhosin and openbasedir must have been broken recently then as I know it worked fine before! - Double check the daemon is running (and so the changes are attempting to be made?)

**Comment by TGates71** [comment]
Yes, I was on wrong branch :( I don't think the current test version is tagged properly then if the cgi stuff is still in there.

**Comment by bobsta63** [comment]
I can confirm after testing this evening on my development box that this doesn't affect the 'master' branch :)

![edit_package](https://cloud.githubusercontent.com/assets/767628/5888708/6b731ef8-a402-11e4-862c-ae8e314250a5.png)

![edit_package2](https://cloud.githubusercontent.com/assets/767628/5888707/6b6edd34-a402-11e4-9e24-32311bdc4805.png)

I will therefore close this bug as I can confirm that all is ok!
